package dev.aster.vega.expression

import dev.aster.vega.model.DiagnosticCodes
import dev.aster.vega.model.DiagnosticSeverity
import dev.aster.vega.model.VegaDiagnostic
import dev.aster.vega.model.VegaValue
import dev.aster.vega.model.asString

/**
 * Raised when an expression cannot be evaluated: an unknown function, or one this engine does not
 * implement.
 *
 * Carries a structured diagnostic so the runtime can surface it through
 * `VegaChartController.diagnostics` rather than swallowing it (PROJECT_BRIEF.md 14).
 */
public class ExpressionEvaluationException(public val diagnostic: VegaDiagnostic) :
  Exception(diagnostic.toString())

/**
 * Tree-walking evaluator for a parsed Vega expression.
 *
 * Walks the AST directly. No `eval`, no reflection-based dispatch, no generated bytecode
 * (PROJECT_BRIEF.md 6.1): functions are looked up in a plain map, so what can run is exactly what
 * [Functions] declares.
 *
 * Stateless and therefore safe to share; all per-evaluation state lives in the [ExpressionScope]
 * argument.
 */
public class Evaluator(
  private val functions: Map<String, ExpressionFunction> = Functions.functions,
  private val constants: Map<String, VegaValue> = Functions.constants,
) {

  public fun evaluate(node: Node, scope: ExpressionScope): VegaValue =
    when (node) {
      is Node.Literal -> node.value
      is Node.Identifier -> identifier(node, scope)
      is Node.Member -> member(node, scope)
      is Node.Call -> call(node, scope)
      is Node.Unary -> unary(node, scope)
      is Node.Binary -> binary(node, scope)
      is Node.Logical -> logical(node, scope)
      is Node.Conditional ->
        if (JsSemantics.truthy(evaluate(node.test, scope))) evaluate(node.consequent, scope)
        else evaluate(node.alternate, scope)
      is Node.ArrayLiteral -> VegaValue.Arr(node.elements.map { evaluate(it, scope) })
      is Node.ObjectLiteral ->
        VegaValue.Obj(
          LinkedHashMap<String, VegaValue>(node.entries.size).apply {
            node.entries.forEach { (key, value) ->
              put(evaluate(key, scope).asString(), evaluate(value, scope))
            }
          }
        )
    }

  private fun identifier(node: Node.Identifier, scope: ExpressionScope): VegaValue =
    when (node.name) {
      "datum" -> scope.datum
      else -> constants[node.name] ?: scope.signal(node.name)
    }

  private fun member(node: Node.Member, scope: ExpressionScope): VegaValue {
    val target = evaluate(node.target, scope)
    val key =
      if (node.computed) evaluate(node.property, scope)
      else VegaValue.Str((node.property as Node.Identifier).name)
    return property(target, key)
  }

  /**
   * Reads one property or element.
   *
   * `length` on a string or array is a property in JavaScript, not a method, and Vega expressions
   * rely on that. A missing property yields null rather than raising, matching how Vega treats
   * absent datum fields.
   */
  private fun property(target: VegaValue, key: VegaValue): VegaValue =
    when (target) {
      is VegaValue.Obj -> target.fields[key.asString()] ?: VegaValue.Null
      is VegaValue.Arr -> {
        val name = key.asString()
        if (name == "length") {
          VegaValue.Num(target.values.size.toDouble())
        } else {
          val index = JsSemantics.toNumber(key)
          if (index.isNaN() || index < 0 || index >= target.values.size) VegaValue.Null
          else target.values[index.toInt()]
        }
      }
      is VegaValue.Str -> {
        val name = key.asString()
        if (name == "length") {
          VegaValue.Num(target.value.length.toDouble())
        } else {
          val index = JsSemantics.toNumber(key)
          if (index.isNaN() || index < 0 || index >= target.value.length) VegaValue.Null
          else VegaValue.Str(target.value[index.toInt()].toString())
        }
      }
      else -> VegaValue.Null
    }

  private fun call(node: Node.Call, scope: ExpressionScope): VegaValue {
    val name =
      when (val callee = node.callee) {
        is Node.Identifier -> callee.name
        // `datum.foo()` has no meaning in Vega's language; there are no methods.
        else ->
          throw ExpressionEvaluationException(
            VegaDiagnostic(
              severity = DiagnosticSeverity.ERROR,
              code = DiagnosticCodes.EXPRESSION_UNSUPPORTED_FUNCTION,
              message =
                "Only named functions can be called; method calls are not part of the language",
            )
          )
      }

    // `if` must short-circuit, so it cannot go through the ordinary argument-evaluation path.
    if (name == "if") {
      if (node.arguments.size != 3) {
        throw ExpressionEvaluationException(
          VegaDiagnostic(
            severity = DiagnosticSeverity.ERROR,
            code = DiagnosticCodes.EXPRESSION_UNSUPPORTED_FUNCTION,
            message = "if() takes exactly three arguments, got ${node.arguments.size}",
          )
        )
      }
      return if (JsSemantics.truthy(evaluate(node.arguments[0], scope))) {
        evaluate(node.arguments[1], scope)
      } else {
        evaluate(node.arguments[2], scope)
      }
    }

    // The one function that writes rather than reads: it empties the named dataset and inserts the
    // rows it is given. Upstream returns 1 from it, and a specification chains on that.
    if (name == "setdata") {
      if (node.arguments.size < 2) {
        throw ExpressionEvaluationException(
          VegaDiagnostic(
            severity = DiagnosticSeverity.ERROR,
            code = DiagnosticCodes.EXPRESSION_UNSUPPORTED_FUNCTION,
            message = "setdata() takes a dataset name and an array of rows",
            operator = name,
          )
        )
      }
      val target = evaluate(node.arguments[0], scope).asString()
      val rows = evaluate(node.arguments[1], scope)
      scope.setDataset(target, (rows as? VegaValue.Arr)?.values ?: listOf(rows))
      return VegaValue.Num(1.0)
    }

    if (name == "treePath" || name == "treeAncestors") {
      val needed = if (name == "treePath") 3 else 2
      if (node.arguments.size < needed) {
        throw ExpressionEvaluationException(
          VegaDiagnostic(
            severity = DiagnosticSeverity.ERROR,
            code = DiagnosticCodes.EXPRESSION_UNSUPPORTED_FUNCTION,
            message = "$name() takes a dataset name and the node(s) to walk between",
            operator = name,
          )
        )
      }
      val dataName = evaluate(node.arguments[0], scope).asString()
      return if (name == "treePath") {
        scope.treePath(
          dataName,
          evaluate(node.arguments[1], scope),
          evaluate(node.arguments[2], scope),
        )
      } else {
        scope.treeAncestors(dataName, evaluate(node.arguments[1], scope))
      }
    }

    // The stochastic family and the clock go through the scope, because both are *state* rather
    // than arithmetic: `random()` answers differently every time it is asked, and `now()` has to be
    // able to stand still while a reference is being compared against. Upstream keeps the first in
    // a module-level binding `setRandom` replaces and code-generates the second as `Date.now`;
    // this engine puts a stream and a clock on the scope so a compile owns both.
    if (name == "random" || name == "now") {
      return VegaValue.Num(if (name == "now") scope.now() else scope.random.next())
    }
    if (name == "sampleNormal" || name == "sampleLogNormal" || name == "sampleUniform") {
      val first = node.arguments.getOrNull(0)?.let { JsSemantics.toNumber(evaluate(it, scope)) }
      val second = node.arguments.getOrNull(1)?.let { JsSemantics.toNumber(evaluate(it, scope)) }
      return VegaValue.Num(
        when (name) {
          "sampleNormal" -> scope.random.sampleNormal(first, second)
          "sampleLogNormal" -> scope.random.sampleLogNormal(first, second)
          else -> scope.random.sampleUniform(first, second)
        }
      )
    }

    if (name == "data") {
      val dataset = scope.dataset(evaluate(node.arguments.first(), scope).asString())
      return VegaValue.Arr(dataset)
    }

    // `indata` reaches the datasets the same way `data` does, through the scope, because the
    // evaluator has none of its own. Upstream additionally *requires* the first two arguments to be
    // string literals, since it resolves them into an index at parse time; nothing here needs them
    // early, so they are evaluated like any other argument and a computed dataset name works.
    if (name == "indata") {
      if (node.arguments.size != 3) {
        throw ExpressionEvaluationException(
          VegaDiagnostic(
            severity = DiagnosticSeverity.ERROR,
            code = DiagnosticCodes.EXPRESSION_UNSUPPORTED_FUNCTION,
            message = "indata() takes a dataset name, a field name and a value",
            operator = name,
          )
        )
      }
      return scope.indata(
        evaluate(node.arguments[0], scope).asString(),
        evaluate(node.arguments[1], scope).asString(),
        evaluate(node.arguments[2], scope),
      )
    }

    // `scale` and `invert` reach out to the chart's scales, which the evaluator cannot know about.
    // The scope answers instead, values in and values out, so this module stays free of any scale
    // type. A third argument names a group scope upstream; there is no equivalent here, so it is
    // reported rather than quietly ignored.
    // `domain`, `range` and `bandwidth` each take a scale name and read a property of it, so they
    // go through the scope for the same reason `scale` does: this module knows nothing of scales.
    if (name == "domain" || name == "range" || name == "bandwidth") {
      if (node.arguments.isEmpty()) {
        throw ExpressionEvaluationException(
          VegaDiagnostic(
            severity = DiagnosticSeverity.ERROR,
            code = DiagnosticCodes.EXPRESSION_UNSUPPORTED_FUNCTION,
            message = "$name() takes a scale name",
            operator = name,
          )
        )
      }
      val scaleName = evaluate(node.arguments[0], scope).asString()
      return when (name) {
        "domain" -> scope.scaleDomain(scaleName)
        "range" -> scope.scaleRange(scaleName)
        else -> scope.scaleBandwidth(scaleName)
      }
    }

    if (name == "scale" || name == "invert") {
      if (node.arguments.size < 2) {
        throw ExpressionEvaluationException(
          VegaDiagnostic(
            severity = DiagnosticSeverity.ERROR,
            code = DiagnosticCodes.EXPRESSION_UNSUPPORTED_FUNCTION,
            message = "$name() takes a scale name and a value",
            operator = name,
          )
        )
      }
      if (node.arguments.size > 2) {
        throw ExpressionEvaluationException(
          VegaDiagnostic(
            severity = DiagnosticSeverity.ERROR,
            code = DiagnosticCodes.EXPRESSION_UNSUPPORTED_FUNCTION,
            message =
              "$name() with a group argument selects a scale from another scope, which has no " +
                "equivalent here",
            operator = name,
          )
        )
      }
      val scaleName = evaluate(node.arguments[0], scope).asString()
      val argument = evaluate(node.arguments[1], scope)
      return if (name == "scale") scope.applyScale(scaleName, argument)
      else scope.invertScale(scaleName, argument)
    }

    // `warn`, `info` and `debug` say something and hand back their **last** argument, so wrapping a
    // value in one leaves the expression computing the same thing. The message goes to whatever
    // sink
    // the scope has; the value comes back either way.
    if (name == "warn" || name == "info" || name == "debug") {
      val values = node.arguments.map { evaluate(it, scope) }
      scope.log(name, values.joinToString(" ") { it.asString() })
      return values.lastOrNull() ?: VegaValue.Null
    }

    /*
     * `modify(name, insert, remove, toggle, modify, values)` — a dataset changed from an expression.
     *
     * The one write besides `setdata`, and the interactive one: a click handler adds the clicked row
     * to a selection dataset with `modify('sel', datum)` and removes it again with a `toggle`. Every
     * argument is optional and the order is upstream's.
     *
     * Returns **0 when there is nothing to do** — no rows in the dataset and nothing to insert or
     * toggle — and 1 otherwise, which is upstream's own early exit and worth keeping: a specification
     * can tell whether its change landed.
     */
    if (name == "modify" && node.arguments.isNotEmpty()) {
      val dataset = evaluate(node.arguments[0], scope).asString()
      val insert = node.arguments.getOrNull(1)?.let { evaluate(it, scope) } ?: VegaValue.Null
      val remove = node.arguments.getOrNull(2)?.let { evaluate(it, scope) } ?: VegaValue.Null
      val toggle = node.arguments.getOrNull(3)?.let { evaluate(it, scope) } ?: VegaValue.Null
      return VegaValue.Num(scope.modifyDataset(dataset, insert, remove, toggle))
    }

    /*
     * `encode(item, name, retval)` — an item re-encoded through one of its own encode sets.
     *
     * A hover handler writes `encode(item, 'hover')` and the item takes its `hover` block. The value
     * is the third argument when there is one and the **item** otherwise, so the common form returns
     * what it was handed. With no item there is nothing to encode and the value comes back unchanged,
     * which is upstream's guard rather than an omission.
     */
    if (name == "encode" && node.arguments.isNotEmpty()) {
      val item = evaluate(node.arguments[0], scope)
      val set = node.arguments.getOrNull(1)?.let { evaluate(it, scope).asString() } ?: "update"
      val fallback = node.arguments.getOrNull(2)?.let { evaluate(it, scope) }
      if (item !is VegaValue.Null) scope.encodeItem(item, set)
      return fallback ?: item
    }

    /*
     * `isTuple(x)` — whether the value is a **row of a dataset** rather than an object written down.
     *
     * Upstream answers from identity: every tuple its dataflow produces carries an id under a Symbol,
     * and `isTuple` looks for it. This engine's rows are plain objects and attaching an id to all of
     * them would cost the whole value model — memory, equality, serialisation — for one predicate.
     *
     * So the question is answered from **origin** instead, which is what that id records anyway: the
     * argument is a tuple when it *came from* the data. `datum`, anything reached through it, an
     * element of `data('name')`, and a scene item's `.datum` are tuples; an object or array literal is
     * not, and neither is a number, a string or null. Every one of those was probed and every one
     * agrees.
     *
     * What this cannot see is a value **laundered through a signal**: `isTuple(mySignal)` is false
     * here whatever the signal holds, where upstream would answer from the value. A signal holding a
     * row is not something a specification writes — probed: a signal holding an object *literal* is
     * false on both sides — but it is the edge, and it is stated rather than hidden.
     */
    if (name == "isTuple" && node.arguments.isNotEmpty()) {
      return VegaValue.Bool(fromData(node.arguments[0]))
    }

    /*
     * The `vlSelection*` family: a selection is an ordinary dataset, so these read one by name.
     *
     * `vlSelectionTuples` is the odd one out — it takes the *items* rather than a dataset name,
     * because a Vega-Lite brush hands it the scene items it just collected.
     */
    if (name == "vlSelectionTest" && node.arguments.size >= 2) {
      val dataset = scope.dataset(evaluate(node.arguments[0], scope).asString())
      val datum = evaluate(node.arguments[1], scope)
      val op = node.arguments.getOrNull(2)?.let { evaluate(it, scope).asString() }
      return VegaValue.Bool(Selections.test(dataset, datum, op))
    }
    if (name == "vlSelectionIdTest" && node.arguments.size >= 2) {
      val dataset = scope.dataset(evaluate(node.arguments[0], scope).asString())
      val datum = evaluate(node.arguments[1], scope)
      val op = node.arguments.getOrNull(2)?.let { evaluate(it, scope).asString() }
      return VegaValue.Bool(Selections.idTest(dataset, datum, op))
    }
    if (name == "vlSelectionResolve" && node.arguments.isNotEmpty()) {
      val dataset = scope.dataset(evaluate(node.arguments[0], scope).asString())
      val op = node.arguments.getOrNull(1)?.let { evaluate(it, scope).asString() }
      val isMulti =
        node.arguments.getOrNull(2)?.let { JsSemantics.truthy(evaluate(it, scope)) } ?: false
      val vl5 =
        node.arguments.getOrNull(3)?.let { JsSemantics.truthy(evaluate(it, scope)) } ?: false
      return Selections.resolve(dataset, op, isMulti, vl5)
    }
    if (name == "vlSelectionTuples" && node.arguments.size >= 2) {
      val items = (evaluate(node.arguments[0], scope) as? VegaValue.Arr)?.values.orEmpty()
      return Selections.tuples(items, evaluate(node.arguments[1], scope))
    }

    // `inScope(item)` — whether the item sits inside the group the expression belongs to.
    if (name == "inScope" && node.arguments.isNotEmpty()) {
      return VegaValue.Bool(scope.inScope(evaluate(node.arguments[0], scope)))
    }

    // `intersect(box[, opt])` and `intersectLasso(mark, points, unit)` — what a region covers.
    if (name == "intersect" && node.arguments.isNotEmpty()) {
      return scope.intersect(
        evaluate(node.arguments[0], scope),
        node.arguments.getOrNull(1)?.let { evaluate(it, scope) } ?: VegaValue.Null,
      )
    }
    if (name == "intersectLasso" && node.arguments.size >= 2) {
      return scope.intersectLasso(
        evaluate(node.arguments[0], scope).asString(),
        evaluate(node.arguments[1], scope),
        node.arguments.getOrNull(2)?.let { evaluate(it, scope) } ?: VegaValue.Null,
      )
    }

    // `gradient(scale, p0, p1[, count])` — the scale's ramp, as a paint value.
    if (name == "gradient" && node.arguments.size >= 3) {
      return scope.gradient(
        evaluate(node.arguments[0], scope).asString(),
        evaluate(node.arguments[1], scope),
        evaluate(node.arguments[2], scope),
        node.arguments.getOrNull(3)?.let { evaluate(it, scope) } ?: VegaValue.Null,
      )
    }

    // `geoShape(projection, feature)` — the outline, as a path this engine's `shape` channel takes.
    if (name == "geoShape" && node.arguments.size >= 2) {
      val projection = evaluate(node.arguments[0], scope)
      val geojson = evaluate(node.arguments[1], scope)
      return scope.geoShape(
        if (projection is VegaValue.Null) null else projection.asString(),
        geojson,
      )
    }

    // `geoCentroid(projection, feature)`, where the projection may be null for a measurement on
    // the globe itself rather than on the page.
    if (
      (name == "geoCentroid" || name == "geoArea" || name == "geoBounds") &&
        node.arguments.size >= 2
    ) {
      val projection = evaluate(node.arguments[0], scope)
      val geojson = evaluate(node.arguments[1], scope)
      val named = if (projection is VegaValue.Null) null else projection.asString()
      return when (name) {
        "geoCentroid" -> scope.geoCentroid(named, geojson)
        "geoArea" -> scope.geoArea(named, geojson)
        else -> scope.geoBounds(named, geojson)
      }
    }
    // `geoScale` names a projection and nothing else: it asks the projection about itself rather
    // than measuring a geometry through it.
    if (name == "geoScale" && node.arguments.isNotEmpty()) {
      val projection = evaluate(node.arguments[0], scope)
      return scope.geoScale(if (projection is VegaValue.Null) null else projection.asString())
    }

    val function = functions[name]
    if (function == null) {
      val reason = Functions.knownUnsupported[name]
      throw ExpressionEvaluationException(
        VegaDiagnostic(
          severity = DiagnosticSeverity.ERROR,
          code = DiagnosticCodes.EXPRESSION_UNSUPPORTED_FUNCTION,
          message =
            if (reason != null) "Function '$name' is not implemented: $reason"
            else "Unknown function '$name'",
          operator = name,
        )
      )
    }
    return function.invoke(node.arguments.map { evaluate(it, scope) })
  }

  private fun unary(node: Node.Unary, scope: ExpressionScope): VegaValue {
    val operand = evaluate(node.operand, scope)
    return when (node.operator) {
      "-" -> VegaValue.Num(-JsSemantics.toNumber(operand))
      "+" -> VegaValue.Num(JsSemantics.toNumber(operand))
      "!" -> VegaValue.Bool(!JsSemantics.truthy(operand))
      "~" -> VegaValue.Num(JsSemantics.toInt32(operand).inv().toDouble())
      else -> unsupportedOperator(node.operator)
    }
  }

  private fun binary(node: Node.Binary, scope: ExpressionScope): VegaValue {
    val left = evaluate(node.left, scope)
    val right = evaluate(node.right, scope)
    return when (node.operator) {
      // `+` is the one operator that is not purely arithmetic; see JsSemantics.add.
      "+" -> JsSemantics.add(left, right)
      "-" -> VegaValue.Num(JsSemantics.toNumber(left) - JsSemantics.toNumber(right))
      "*" -> VegaValue.Num(JsSemantics.toNumber(left) * JsSemantics.toNumber(right))
      "/" -> VegaValue.Num(JsSemantics.toNumber(left) / JsSemantics.toNumber(right))
      "%" ->
        VegaValue.Num(
          JsSemantics.remainder(JsSemantics.toNumber(left), JsSemantics.toNumber(right))
        )

      "===" -> VegaValue.Bool(JsSemantics.strictEquals(left, right))
      "!==" -> VegaValue.Bool(!JsSemantics.strictEquals(left, right))
      "==" -> VegaValue.Bool(JsSemantics.looseEquals(left, right))
      "!=" -> VegaValue.Bool(!JsSemantics.looseEquals(left, right))

      // A NaN operand makes every relational comparison false, which is why compare returns null.
      "<" -> VegaValue.Bool(JsSemantics.compare(left, right)?.let { it < 0 } ?: false)
      "<=" -> VegaValue.Bool(JsSemantics.compare(left, right)?.let { it <= 0 } ?: false)
      ">" -> VegaValue.Bool(JsSemantics.compare(left, right)?.let { it > 0 } ?: false)
      ">=" -> VegaValue.Bool(JsSemantics.compare(left, right)?.let { it >= 0 } ?: false)

      "&" -> VegaValue.Num((JsSemantics.toInt32(left) and JsSemantics.toInt32(right)).toDouble())
      "|" -> VegaValue.Num((JsSemantics.toInt32(left) or JsSemantics.toInt32(right)).toDouble())
      "^" -> VegaValue.Num((JsSemantics.toInt32(left) xor JsSemantics.toInt32(right)).toDouble())
      // JavaScript masks the shift count to five bits.
      "<<" ->
        VegaValue.Num(
          (JsSemantics.toInt32(left) shl (JsSemantics.toInt32(right) and 31)).toDouble()
        )
      ">>" ->
        VegaValue.Num(
          (JsSemantics.toInt32(left) shr (JsSemantics.toInt32(right) and 31)).toDouble()
        )
      ">>>" ->
        VegaValue.Num(
          (JsSemantics.toUint32(left) ushr (JsSemantics.toInt32(right) and 31)).toDouble()
        )

      else -> unsupportedOperator(node.operator)
    }
  }

  /**
   * `&&` and `||` return one of their operands, not a boolean, and skip the right side when they
   * can.
   */
  private fun logical(node: Node.Logical, scope: ExpressionScope): VegaValue {
    val left = evaluate(node.left, scope)
    return when (node.operator) {
      "&&" -> if (!JsSemantics.truthy(left)) left else evaluate(node.right, scope)
      "||" -> if (JsSemantics.truthy(left)) left else evaluate(node.right, scope)
      else -> unsupportedOperator(node.operator)
    }
  }

  private fun unsupportedOperator(operator: String): Nothing =
    throw ExpressionEvaluationException(
      VegaDiagnostic(
        severity = DiagnosticSeverity.ERROR,
        code = DiagnosticCodes.EXPRESSION_PARSE_ERROR,
        message = "Unsupported operator '$operator'",
      )
    )

  /**
   * Whether an expression names something that came out of the data, for `isTuple`.
   *
   * Walks the syntax rather than the value, because that is where the provenance still is. `datum`
   * and `data(...)` are the two roots; a member or an index of either is still data, which is what
   * makes `data('t')[0]` and `item.datum` both tuples.
   */
  private fun fromData(node: Node): Boolean =
    when (node) {
      is Node.Identifier -> node.name == "datum"
      // `item.datum` is a tuple wherever the item came from, and so is anything reached through
      // one — `data('t')[0]` is an index, `datum.nested` a member.
      is Node.Member ->
        (node.property as? Node.Identifier)?.name == "datum" || fromData(node.target)
      is Node.Call ->
        (node.callee as? Node.Identifier)?.name.let { it == "data" || it == "treePath" }
      else -> false
    }
}
