package dev.aster.vega.expression

import dev.aster.vega.model.DiagnosticCodes
import dev.aster.vega.model.DiagnosticSeverity
import dev.aster.vega.model.VegaDiagnostic
import dev.aster.vega.model.VegaValue
import dev.aster.vega.model.asString

/**
 * Raised when an expression cannot be evaluated: an unknown function, or one this engine does not
 * implement.
 *
 * Carries a structured diagnostic so the runtime can surface it through
 * `VegaChartController.diagnostics` rather than swallowing it (PROJECT_BRIEF.md 14).
 */
public class ExpressionEvaluationException(public val diagnostic: VegaDiagnostic) :
  Exception(diagnostic.toString())

/**
 * Tree-walking evaluator for a parsed Vega expression.
 *
 * Walks the AST directly. No `eval`, no reflection-based dispatch, no generated bytecode
 * (PROJECT_BRIEF.md 6.1): functions are looked up in a plain map, so what can run is exactly what
 * [Functions] declares.
 *
 * Stateless and therefore safe to share; all per-evaluation state lives in the [ExpressionScope]
 * argument.
 */
public class Evaluator(
  private val functions: Map<String, ExpressionFunction> = Functions.functions,
  private val constants: Map<String, VegaValue> = Functions.constants,
) {

  public fun evaluate(node: Node, scope: ExpressionScope): VegaValue =
    when (node) {
      is Node.Literal -> node.value
      is Node.Identifier -> identifier(node, scope)
      is Node.Member -> member(node, scope)
      is Node.Call -> call(node, scope)
      is Node.Unary -> unary(node, scope)
      is Node.Binary -> binary(node, scope)
      is Node.Logical -> logical(node, scope)
      is Node.Conditional ->
        if (JsSemantics.truthy(evaluate(node.test, scope))) evaluate(node.consequent, scope)
        else evaluate(node.alternate, scope)
      is Node.ArrayLiteral -> VegaValue.Arr(node.elements.map { evaluate(it, scope) })
      is Node.ObjectLiteral ->
        VegaValue.Obj(
          LinkedHashMap<String, VegaValue>(node.entries.size).apply {
            node.entries.forEach { (key, value) ->
              put(evaluate(key, scope).asString(), evaluate(value, scope))
            }
          }
        )
    }

  private fun identifier(node: Node.Identifier, scope: ExpressionScope): VegaValue =
    when (node.name) {
      "datum" -> scope.datum
      else -> constants[node.name] ?: scope.signal(node.name)
    }

  private fun member(node: Node.Member, scope: ExpressionScope): VegaValue {
    val target = evaluate(node.target, scope)
    val key =
      if (node.computed) evaluate(node.property, scope)
      else VegaValue.Str((node.property as Node.Identifier).name)
    return property(target, key)
  }

  /**
   * Reads one property or element.
   *
   * `length` on a string or array is a property in JavaScript, not a method, and Vega expressions
   * rely on that. A missing property yields null rather than raising, matching how Vega treats
   * absent datum fields.
   */
  private fun property(target: VegaValue, key: VegaValue): VegaValue =
    when (target) {
      is VegaValue.Obj -> target.fields[key.asString()] ?: VegaValue.Null
      is VegaValue.Arr -> {
        val name = key.asString()
        if (name == "length") {
          VegaValue.Num(target.values.size.toDouble())
        } else {
          val index = JsSemantics.toNumber(key)
          if (index.isNaN() || index < 0 || index >= target.values.size) VegaValue.Null
          else target.values[index.toInt()]
        }
      }
      is VegaValue.Str -> {
        val name = key.asString()
        if (name == "length") {
          VegaValue.Num(target.value.length.toDouble())
        } else {
          val index = JsSemantics.toNumber(key)
          if (index.isNaN() || index < 0 || index >= target.value.length) VegaValue.Null
          else VegaValue.Str(target.value[index.toInt()].toString())
        }
      }
      else -> VegaValue.Null
    }

  private fun call(node: Node.Call, scope: ExpressionScope): VegaValue {
    val name =
      when (val callee = node.callee) {
        is Node.Identifier -> callee.name
        // `datum.foo()` has no meaning in Vega's language; there are no methods.
        else ->
          throw ExpressionEvaluationException(
            VegaDiagnostic(
              severity = DiagnosticSeverity.ERROR,
              code = DiagnosticCodes.EXPRESSION_UNSUPPORTED_FUNCTION,
              message =
                "Only named functions can be called; method calls are not part of the language",
            )
          )
      }

    // `if` must short-circuit, so it cannot go through the ordinary argument-evaluation path.
    if (name == "if") {
      if (node.arguments.size != 3) {
        throw ExpressionEvaluationException(
          VegaDiagnostic(
            severity = DiagnosticSeverity.ERROR,
            code = DiagnosticCodes.EXPRESSION_UNSUPPORTED_FUNCTION,
            message = "if() takes exactly three arguments, got ${node.arguments.size}",
          )
        )
      }
      return if (JsSemantics.truthy(evaluate(node.arguments[0], scope))) {
        evaluate(node.arguments[1], scope)
      } else {
        evaluate(node.arguments[2], scope)
      }
    }

    // The one function that writes rather than reads: it empties the named dataset and inserts the
    // rows it is given. Upstream returns 1 from it, and a specification chains on that.
    if (name == "setdata") {
      if (node.arguments.size < 2) {
        throw ExpressionEvaluationException(
          VegaDiagnostic(
            severity = DiagnosticSeverity.ERROR,
            code = DiagnosticCodes.EXPRESSION_UNSUPPORTED_FUNCTION,
            message = "setdata() takes a dataset name and an array of rows",
            operator = name,
          )
        )
      }
      val target = evaluate(node.arguments[0], scope).asString()
      val rows = evaluate(node.arguments[1], scope)
      scope.setDataset(target, (rows as? VegaValue.Arr)?.values ?: listOf(rows))
      return VegaValue.Num(1.0)
    }

    if (name == "treePath" || name == "treeAncestors") {
      val needed = if (name == "treePath") 3 else 2
      if (node.arguments.size < needed) {
        throw ExpressionEvaluationException(
          VegaDiagnostic(
            severity = DiagnosticSeverity.ERROR,
            code = DiagnosticCodes.EXPRESSION_UNSUPPORTED_FUNCTION,
            message = "$name() takes a dataset name and the node(s) to walk between",
            operator = name,
          )
        )
      }
      val dataName = evaluate(node.arguments[0], scope).asString()
      return if (name == "treePath") {
        scope.treePath(
          dataName,
          evaluate(node.arguments[1], scope),
          evaluate(node.arguments[2], scope),
        )
      } else {
        scope.treeAncestors(dataName, evaluate(node.arguments[1], scope))
      }
    }

    if (name == "data") {
      val dataset = scope.dataset(evaluate(node.arguments.first(), scope).asString())
      return VegaValue.Arr(dataset)
    }

    // `indata` reaches the datasets the same way `data` does, through the scope, because the
    // evaluator has none of its own. Upstream additionally *requires* the first two arguments to be
    // string literals, since it resolves them into an index at parse time; nothing here needs them
    // early, so they are evaluated like any other argument and a computed dataset name works.
    if (name == "indata") {
      if (node.arguments.size != 3) {
        throw ExpressionEvaluationException(
          VegaDiagnostic(
            severity = DiagnosticSeverity.ERROR,
            code = DiagnosticCodes.EXPRESSION_UNSUPPORTED_FUNCTION,
            message = "indata() takes a dataset name, a field name and a value",
            operator = name,
          )
        )
      }
      return scope.indata(
        evaluate(node.arguments[0], scope).asString(),
        evaluate(node.arguments[1], scope).asString(),
        evaluate(node.arguments[2], scope),
      )
    }

    // `scale` and `invert` reach out to the chart's scales, which the evaluator cannot know about.
    // The scope answers instead, values in and values out, so this module stays free of any scale
    // type. A third argument names a group scope upstream; there is no equivalent here, so it is
    // reported rather than quietly ignored.
    // `domain`, `range` and `bandwidth` each take a scale name and read a property of it, so they
    // go through the scope for the same reason `scale` does: this module knows nothing of scales.
    if (name == "domain" || name == "range" || name == "bandwidth") {
      if (node.arguments.isEmpty()) {
        throw ExpressionEvaluationException(
          VegaDiagnostic(
            severity = DiagnosticSeverity.ERROR,
            code = DiagnosticCodes.EXPRESSION_UNSUPPORTED_FUNCTION,
            message = "$name() takes a scale name",
            operator = name,
          )
        )
      }
      val scaleName = evaluate(node.arguments[0], scope).asString()
      return when (name) {
        "domain" -> scope.scaleDomain(scaleName)
        "range" -> scope.scaleRange(scaleName)
        else -> scope.scaleBandwidth(scaleName)
      }
    }

    if (name == "scale" || name == "invert") {
      if (node.arguments.size < 2) {
        throw ExpressionEvaluationException(
          VegaDiagnostic(
            severity = DiagnosticSeverity.ERROR,
            code = DiagnosticCodes.EXPRESSION_UNSUPPORTED_FUNCTION,
            message = "$name() takes a scale name and a value",
            operator = name,
          )
        )
      }
      if (node.arguments.size > 2) {
        throw ExpressionEvaluationException(
          VegaDiagnostic(
            severity = DiagnosticSeverity.ERROR,
            code = DiagnosticCodes.EXPRESSION_UNSUPPORTED_FUNCTION,
            message =
              "$name() with a group argument selects a scale from another scope, which has no " +
                "equivalent here",
            operator = name,
          )
        )
      }
      val scaleName = evaluate(node.arguments[0], scope).asString()
      val argument = evaluate(node.arguments[1], scope)
      return if (name == "scale") scope.applyScale(scaleName, argument)
      else scope.invertScale(scaleName, argument)
    }

    val function = functions[name]
    if (function == null) {
      val reason = Functions.knownUnsupported[name]
      throw ExpressionEvaluationException(
        VegaDiagnostic(
          severity = DiagnosticSeverity.ERROR,
          code = DiagnosticCodes.EXPRESSION_UNSUPPORTED_FUNCTION,
          message =
            if (reason != null) "Function '$name' is not implemented: $reason"
            else "Unknown function '$name'",
          operator = name,
        )
      )
    }
    return function.invoke(node.arguments.map { evaluate(it, scope) })
  }

  private fun unary(node: Node.Unary, scope: ExpressionScope): VegaValue {
    val operand = evaluate(node.operand, scope)
    return when (node.operator) {
      "-" -> VegaValue.Num(-JsSemantics.toNumber(operand))
      "+" -> VegaValue.Num(JsSemantics.toNumber(operand))
      "!" -> VegaValue.Bool(!JsSemantics.truthy(operand))
      "~" -> VegaValue.Num(JsSemantics.toInt32(operand).inv().toDouble())
      else -> unsupportedOperator(node.operator)
    }
  }

  private fun binary(node: Node.Binary, scope: ExpressionScope): VegaValue {
    val left = evaluate(node.left, scope)
    val right = evaluate(node.right, scope)
    return when (node.operator) {
      // `+` is the one operator that is not purely arithmetic; see JsSemantics.add.
      "+" -> JsSemantics.add(left, right)
      "-" -> VegaValue.Num(JsSemantics.toNumber(left) - JsSemantics.toNumber(right))
      "*" -> VegaValue.Num(JsSemantics.toNumber(left) * JsSemantics.toNumber(right))
      "/" -> VegaValue.Num(JsSemantics.toNumber(left) / JsSemantics.toNumber(right))
      "%" ->
        VegaValue.Num(
          JsSemantics.remainder(JsSemantics.toNumber(left), JsSemantics.toNumber(right))
        )

      "===" -> VegaValue.Bool(JsSemantics.strictEquals(left, right))
      "!==" -> VegaValue.Bool(!JsSemantics.strictEquals(left, right))
      "==" -> VegaValue.Bool(JsSemantics.looseEquals(left, right))
      "!=" -> VegaValue.Bool(!JsSemantics.looseEquals(left, right))

      // A NaN operand makes every relational comparison false, which is why compare returns null.
      "<" -> VegaValue.Bool(JsSemantics.compare(left, right)?.let { it < 0 } ?: false)
      "<=" -> VegaValue.Bool(JsSemantics.compare(left, right)?.let { it <= 0 } ?: false)
      ">" -> VegaValue.Bool(JsSemantics.compare(left, right)?.let { it > 0 } ?: false)
      ">=" -> VegaValue.Bool(JsSemantics.compare(left, right)?.let { it >= 0 } ?: false)

      "&" -> VegaValue.Num((JsSemantics.toInt32(left) and JsSemantics.toInt32(right)).toDouble())
      "|" -> VegaValue.Num((JsSemantics.toInt32(left) or JsSemantics.toInt32(right)).toDouble())
      "^" -> VegaValue.Num((JsSemantics.toInt32(left) xor JsSemantics.toInt32(right)).toDouble())
      // JavaScript masks the shift count to five bits.
      "<<" ->
        VegaValue.Num(
          (JsSemantics.toInt32(left) shl (JsSemantics.toInt32(right) and 31)).toDouble()
        )
      ">>" ->
        VegaValue.Num(
          (JsSemantics.toInt32(left) shr (JsSemantics.toInt32(right) and 31)).toDouble()
        )
      ">>>" ->
        VegaValue.Num(
          (JsSemantics.toUint32(left) ushr (JsSemantics.toInt32(right) and 31)).toDouble()
        )

      else -> unsupportedOperator(node.operator)
    }
  }

  /**
   * `&&` and `||` return one of their operands, not a boolean, and skip the right side when they
   * can.
   */
  private fun logical(node: Node.Logical, scope: ExpressionScope): VegaValue {
    val left = evaluate(node.left, scope)
    return when (node.operator) {
      "&&" -> if (!JsSemantics.truthy(left)) left else evaluate(node.right, scope)
      "||" -> if (JsSemantics.truthy(left)) left else evaluate(node.right, scope)
      else -> unsupportedOperator(node.operator)
    }
  }

  private fun unsupportedOperator(operator: String): Nothing =
    throw ExpressionEvaluationException(
      VegaDiagnostic(
        severity = DiagnosticSeverity.ERROR,
        code = DiagnosticCodes.EXPRESSION_PARSE_ERROR,
        message = "Unsupported operator '$operator'",
      )
    )
}
