package dev.aster.vega.expression

import dev.aster.vega.model.DiagnosticCodes
import dev.aster.vega.model.VegaDiagnostic
import dev.aster.vega.model.VegaValue
import dev.aster.vega.model.asString
import dev.aster.vega.model.field

/**
 * Expression API surface.
 *
 * Milestone 0 fixes the contracts; the lexer, parser and evaluator arrive with the dataflow in
 * Milestone 4 (PROJECT_BRIEF.md 20). Two rules are load-bearing and encoded here rather than left
 * to the implementation:
 * - no `eval`, JavaScript, reflection-based dispatch or generated bytecode (PROJECT_BRIEF.md 6.1)
 * - an unknown function is a diagnostic, never a silent `null`
 */
public interface Expression {
  /** The original source text, kept for diagnostics and debugging. */
  public val source: String

  /** Signal names this expression reads, so the dataflow knows what to invalidate. */
  public val signalDependencies: Set<String>

  /** Datum field paths this expression reads. */
  public val fieldDependencies: Set<String>

  /**
   * Datasets this expression names outright: the string literal a `data()` or `indata()` is given.
   *
   * Upstream's `dataVisitor` reads the same argument at parse time and turns it into a parameter of
   * the operator the expression belongs to, which is what puts the dataset ahead of it in the
   * dataflow's ranking. Naming them here buys the same ordering, so a scale domain or a transform
   * parameter written as an expression can be resolved after the datasets it reads.
   */
  public val dataDependencies: Set<String>

  /**
   * True when a dataset is named by an expression rather than a literal, as in `data(chosen)`.
   *
   * There is no name to record, so anything ordering itself against this expression has to wait for
   * *every* dataset. Upstream refuses the case outright — "First argument to data functions must be
   * a string literal" — and this engine evaluates it instead, so the ordering has to cover it.
   */
  public val readsUnnamedDataset: Boolean

  /**
   * Scales this expression names outright, through `scale`, `invert`, `domain`, `range` or
   * `bandwidth`.
   *
   * The counterpart of [dataDependencies] for upstream's `scaleVisitor`, and the reason a signal
   * reading `domain('xscale')` can be resolved once that one scale exists rather than not at all.
   */
  public val scaleDependencies: Set<String>

  /**
   * True when a scale is named by an expression rather than a literal, as in `scale(which, v)`.
   *
   * Upstream's `scaleVisitor` makes *every* scale in the enclosing scope a dependency in this case,
   * because there is no way to tell which one will be asked for.
   */
  public val readsUnnamedScale: Boolean

  /**
   * Datasets this expression *replaces*, through `setdata`.
   *
   * The mirror of [dataDependencies]: anything reading one of these has to be ordered behind the
   * expression rather than in front of it.
   */
  public val writtenDatasets: Set<String>

  public fun evaluate(scope: ExpressionScope): VegaValue
}

/** Everything an expression can read. Passed explicitly; there is no ambient global scope. */
public interface ExpressionScope {
  /** The current datum, or [VegaValue.Null] outside a mark encoding. */
  public val datum: VegaValue

  public fun signal(name: String): VegaValue

  /** Named datasets, for `data('name')`. */
  public fun dataset(name: String): List<VegaValue>

  /**
   * `indata('name', 'field', value)` — how many rows of the named dataset carry that value.
   *
   * Not a boolean, despite the documentation: upstream returns the **count** of matching rows, or
   * `undefined` when there are none, and a specification that prints the result prints a number.
   * [VegaValue.Null] stands in for that `undefined`; both are falsey, so the usual
   * `if(indata(...))` reads the same either way.
   *
   * The default scans, which is correct and quadratic when called once per datum. A scope that
   * answers many of these — a mark encoding, in practice — should override with an index.
   */
  public fun indata(name: String, field: String, value: VegaValue): VegaValue =
    indataLookup(indataCounts(dataset(name), field), value)

  /**
   * `scale('name', value)` — a scale applied from inside an expression.
   *
   * Values in and values out, so `vega-expression` stays free of any scale type. A scope with no
   * scales returns null, which is what a bare expression evaluated outside a chart should do.
   */
  public fun applyScale(name: String, value: VegaValue): VegaValue = VegaValue.Null

  /** `invert('name', value)` — the same in reverse, for a continuous scale. */
  public fun invertScale(name: String, value: VegaValue): VegaValue = VegaValue.Null

  /** `domain('name')` — the scale's input extent, which a specification reads to size something. */
  public fun scaleDomain(name: String): VegaValue = VegaValue.Null

  /** `range('name')` — the scale's output extent. */
  public fun scaleRange(name: String): VegaValue = VegaValue.Null

  /**
   * `geoCentroid('projection', feature)` — where a shape balances, in projected coordinates.
   *
   * Declared here and implemented where projections live, exactly as `scale()` is: this module
   * knows nothing about geography and should not start. A scope with no projections answers null,
   * which is what a bare expression evaluated outside a chart should do.
   */
  public fun geoCentroid(projection: String?, geojson: VegaValue): VegaValue = VegaValue.Null

  /** `geoArea('projection', feature)` — how much of the page the shape covers. */
  public fun geoArea(projection: String?, geojson: VegaValue): VegaValue = VegaValue.Null

  /** `bandwidth('name')` — a band scale's band width, or zero for a scale that has none. */
  public fun scaleBandwidth(name: String): VegaValue = VegaValue.Num(0.0)

  /**
   * `setdata('name', rows)` — replaces a dataset's contents outright.
   *
   * The one expression function that *writes*. Upstream pulses a changeset that removes everything
   * and inserts the new rows, and returns 1. A scope with nowhere to put them ignores it, which is
   * what a bare expression evaluated outside a chart should do.
   */
  public fun setDataset(name: String, rows: List<VegaValue>) {}

  /**
   * `treePath('name', from, to)` — the rows between two nodes of a stratified dataset.
   *
   * A scope with no tree of that name returns null, which is what upstream returns for a link whose
   * ends are not both in the tree.
   */
  public fun treePath(name: String, from: VegaValue, to: VegaValue): VegaValue = VegaValue.Null

  /** `treeAncestors('name', node)` — that node's row and every ancestor's, the root last. */
  public fun treeAncestors(name: String, node: VegaValue): VegaValue = VegaValue.Null

  /**
   * The stream `random()` and the `sample*` family draw from.
   *
   * On the scope rather than in [Functions] because it is the one family whose answer depends on
   * how many times it has already been asked, and per-evaluation state is what a scope is for.
   * Upstream shares one module-level generator across a whole view, so a chart's picture depends on
   * the order its expressions run in as much as on the generator; handing out a fresh stream per
   * call would be reproducible and would not be upstream.
   */
  public val random: RandomStream
    get() = DetachedStream

  /** `now()` — the instant this compile is pinned to; see [Clock]. */
  public fun now(): Double = Clock.PINNED
}

/**
 * The stream a scope that is not compiling a chart draws from.
 *
 * Shared, and so *not* reproducible across evaluations — which is the point: it exists for a bare
 * expression evaluated in a test, where nothing downstream depends on the sequence. Every scope the
 * runtime builds owns a stream of its own, seeded per compile.
 */
private val DetachedStream = RandomStream()

/**
 * The index upstream's `indata` looks a value up in: string-coerced field value to row count.
 *
 * Upstream builds it with an `aggregate` grouped by the field feeding a `TupleIndex`, whose map is
 * a plain JavaScript object — so the key is the field value **coerced to a string**, and so is the
 * value looked up. That is the whole comparison, and it is not `===`: `indata('t', 'k', 1)` finds a
 * row whose `k` is the string `"1"`, and `indata('t', 'k', true)` finds one whose `k` is `"true"`.
 * Reading the documentation's "matches value" as strict equality gives a chart that is silently
 * missing exactly the rows whose types were not what the specification's author assumed.
 */
public fun indataCounts(rows: List<VegaValue>, field: String): Map<String, Int> =
  rows.groupingBy { it.field(field).asString() }.eachCount()

/** Reads [indataCounts] the way upstream does: the count, or absent rather than zero. */
public fun indataLookup(counts: Map<String, Int>, value: VegaValue): VegaValue =
  counts[value.asString()]?.let { VegaValue.Num(it.toDouble()) } ?: VegaValue.Null

public sealed interface ExpressionResult {
  public data class Compiled(val expression: Expression) : ExpressionResult

  public data class Failed(val diagnostic: VegaDiagnostic) : ExpressionResult
}

/**
 * Parses and caches expressions.
 *
 * Implementations must be free of global mutable state: a compiler instance belongs to one runtime,
 * so clearing or discarding it is always possible.
 */
public interface ExpressionCompiler {
  public fun compile(source: String): ExpressionResult
}

/**
 * Bounded LRU cache in front of an [ExpressionCompiler].
 *
 * Vega specifications reuse the same expression strings across many marks and updates, so caching
 * by source text avoids reparsing. Owned by its creator rather than being a singleton, so its
 * lifetime is controllable (PROJECT_BRIEF.md 21).
 */
public class CachingExpressionCompiler(
  private val delegate: ExpressionCompiler,
  private val maxEntries: Int = 512,
) : ExpressionCompiler {

  private val cache =
    object : LinkedHashMap<String, ExpressionResult>(64, 0.75f, true) {
      override fun removeEldestEntry(
        eldest: MutableMap.MutableEntry<String, ExpressionResult>?
      ): Boolean = size > maxEntries
    }

  public val size: Int
    get() = cache.size

  override fun compile(source: String): ExpressionResult =
    cache.getOrPut(source) {
      delegate.compile(source)
    }

  public fun clear() {
    cache.clear()
  }
}

/**
 * The compiler in place until Milestone 4.
 *
 * It refuses every expression with a structured diagnostic rather than returning a null value, so a
 * specification that needs expressions fails visibly instead of rendering something wrong
 * (PROJECT_BRIEF.md 3.3: "Never silently ignore an unsupported operator").
 */
public class UnsupportedExpressionCompiler : ExpressionCompiler {
  override fun compile(source: String): ExpressionResult =
    ExpressionResult.Failed(
      VegaDiagnostic(
        severity = dev.aster.vega.model.DiagnosticSeverity.ERROR,
        code = DiagnosticCodes.EXPRESSION_UNSUPPORTED_FUNCTION,
        message =
          "Expression evaluation is not implemented yet (planned for Milestone 4): '$source'",
      )
    )
}
