package dev.aster.vega.expression

import dev.aster.vega.model.DiagnosticCodes
import dev.aster.vega.model.VegaDiagnostic
import dev.aster.vega.model.VegaValue

/**
 * Expression API surface.
 *
 * Milestone 0 fixes the contracts; the lexer, parser and evaluator arrive with the dataflow in
 * Milestone 4 (PROJECT_BRIEF.md 20). Two rules are load-bearing and encoded here rather than left
 * to the implementation:
 * - no `eval`, JavaScript, reflection-based dispatch or generated bytecode (PROJECT_BRIEF.md 6.1)
 * - an unknown function is a diagnostic, never a silent `null`
 */
public interface Expression {
  /** The original source text, kept for diagnostics and debugging. */
  public val source: String

  /** Signal names this expression reads, so the dataflow knows what to invalidate. */
  public val signalDependencies: Set<String>

  /** Datum field paths this expression reads. */
  public val fieldDependencies: Set<String>

  public fun evaluate(scope: ExpressionScope): VegaValue
}

/** Everything an expression can read. Passed explicitly; there is no ambient global scope. */
public interface ExpressionScope {
  /** The current datum, or [VegaValue.Null] outside a mark encoding. */
  public val datum: VegaValue

  public fun signal(name: String): VegaValue

  /** Named datasets, for `data('name')`. */
  public fun dataset(name: String): List<VegaValue>

  /**
   * `scale('name', value)` — a scale applied from inside an expression.
   *
   * Values in and values out, so `vega-expression` stays free of any scale type. A scope with no
   * scales returns null, which is what a bare expression evaluated outside a chart should do.
   */
  public fun applyScale(name: String, value: VegaValue): VegaValue = VegaValue.Null

  /** `invert('name', value)` — the same in reverse, for a continuous scale. */
  public fun invertScale(name: String, value: VegaValue): VegaValue = VegaValue.Null
}

public sealed interface ExpressionResult {
  public data class Compiled(val expression: Expression) : ExpressionResult

  public data class Failed(val diagnostic: VegaDiagnostic) : ExpressionResult
}

/**
 * Parses and caches expressions.
 *
 * Implementations must be free of global mutable state: a compiler instance belongs to one runtime,
 * so clearing or discarding it is always possible.
 */
public interface ExpressionCompiler {
  public fun compile(source: String): ExpressionResult
}

/**
 * Bounded LRU cache in front of an [ExpressionCompiler].
 *
 * Vega specifications reuse the same expression strings across many marks and updates, so caching
 * by source text avoids reparsing. Owned by its creator rather than being a singleton, so its
 * lifetime is controllable (PROJECT_BRIEF.md 21).
 */
public class CachingExpressionCompiler(
  private val delegate: ExpressionCompiler,
  private val maxEntries: Int = 512,
) : ExpressionCompiler {

  private val cache =
    object : LinkedHashMap<String, ExpressionResult>(64, 0.75f, true) {
      override fun removeEldestEntry(
        eldest: MutableMap.MutableEntry<String, ExpressionResult>?
      ): Boolean = size > maxEntries
    }

  public val size: Int
    get() = cache.size

  override fun compile(source: String): ExpressionResult =
    cache.getOrPut(source) {
      delegate.compile(source)
    }

  public fun clear() {
    cache.clear()
  }
}

/**
 * The compiler in place until Milestone 4.
 *
 * It refuses every expression with a structured diagnostic rather than returning a null value, so a
 * specification that needs expressions fails visibly instead of rendering something wrong
 * (PROJECT_BRIEF.md 3.3: "Never silently ignore an unsupported operator").
 */
public class UnsupportedExpressionCompiler : ExpressionCompiler {
  override fun compile(source: String): ExpressionResult =
    ExpressionResult.Failed(
      VegaDiagnostic(
        severity = dev.aster.vega.model.DiagnosticSeverity.ERROR,
        code = DiagnosticCodes.EXPRESSION_UNSUPPORTED_FUNCTION,
        message =
          "Expression evaluation is not implemented yet (planned for Milestone 4): '$source'",
      )
    )
}
