package dev.aster.vega.expression

import dev.aster.vega.model.VegaValue

/**
 * Recursive-descent parser with a precedence table, for Vega's expression language.
 *
 * Precedence and associativity follow JavaScript's, because Vega's own implementation compiles
 * expressions to JavaScript and inherits them. Getting this wrong is quietly catastrophic: `a + b *
 * c` would evaluate as `(a + b) * c` and the chart would simply be wrong, with nothing to indicate
 * why.
 *
 * No `eval`, no reflection, no generated bytecode (PROJECT_BRIEF.md 6.1) — the result is a plain
 * tree that [Evaluator] walks.
 */
public class Parser(private val source: String) {

  private val tokens = Lexer(source).tokenize()
  private var position = 0

  public fun parse(): Node {
    val node = parseExpression()
    val token = peek()
    if (token.type != TokenType.END) {
      throw ExpressionSyntaxException("Unexpected '${token.text}'", token.start, source)
    }
    return node
  }

  // ---- precedence climbing --------------------------------------------------

  private fun parseExpression(): Node = parseConditional()

  /** `test ? consequent : alternate`, right-associative. */
  private fun parseConditional(): Node {
    val test = parseBinary(0)
    if (!matchOperator("?")) return test
    val consequent = parseExpression()
    expectPunctuation(":")
    val alternate = parseExpression()
    return Node.Conditional(test, consequent, alternate)
  }

  /**
   * Left-associative binary operators, climbing the precedence table.
   *
   * `&&` and `||` become [Node.Logical] rather than [Node.Binary] because they short-circuit, and
   * the evaluator has to know not to evaluate the right operand.
   */
  private fun parseBinary(minimumPrecedence: Int): Node {
    var left = parseUnary()
    while (true) {
      val token = peek()
      if (token.type != TokenType.OPERATOR) return left
      val precedence = PRECEDENCE[token.text] ?: return left
      if (precedence < minimumPrecedence) return left
      advance()
      val right = parseBinary(precedence + 1)
      left =
        if (token.text == "&&" || token.text == "||") Node.Logical(token.text, left, right)
        else Node.Binary(token.text, left, right)
    }
  }

  private fun parseUnary(): Node {
    val token = peek()
    if (token.type == TokenType.OPERATOR && token.text in UNARY_OPERATORS) {
      advance()
      return Node.Unary(token.text, parseUnary())
    }
    return parsePostfix()
  }

  /** Member access and calls, which bind tighter than any operator and chain left to right. */
  private fun parsePostfix(): Node {
    var node = parsePrimary()
    while (true) {
      node =
        when {
          matchPunctuation(".") -> {
            val name = peek()
            if (name.type != TokenType.IDENTIFIER) {
              throw ExpressionSyntaxException("Expected a property name", name.start, source)
            }
            advance()
            Node.Member(node, Node.Identifier(name.text), computed = false)
          }
          matchPunctuation("[") -> {
            val property = parseExpression()
            expectPunctuation("]")
            Node.Member(node, property, computed = true)
          }
          matchPunctuation("(") -> Node.Call(node, parseArguments())
          else -> return node
        }
    }
  }

  private fun parseArguments(): List<Node> {
    val arguments = mutableListOf<Node>()
    if (matchPunctuation(")")) return arguments
    while (true) {
      arguments.add(parseExpression())
      if (matchPunctuation(",")) continue
      expectPunctuation(")")
      return arguments
    }
  }

  private fun parsePrimary(): Node {
    val token = peek()
    return when {
      token.type == TokenType.NUMBER -> {
        advance()
        Node.Literal(VegaValue.Num(parseNumber(token)))
      }
      token.type == TokenType.STRING -> {
        advance()
        Node.Literal(VegaValue.Str(token.text))
      }
      token.type == TokenType.IDENTIFIER ->
        when (token.text) {
          "true" -> {
            advance()
            Node.Literal(VegaValue.Bool(true))
          }
          "false" -> {
            advance()
            Node.Literal(VegaValue.Bool(false))
          }
          "null" -> {
            advance()
            Node.Literal(VegaValue.Null)
          }
          else -> {
            advance()
            Node.Identifier(token.text)
          }
        }
      matchPunctuation("(") -> {
        val inner = parseExpression()
        expectPunctuation(")")
        inner
      }
      matchPunctuation("[") -> {
        val elements = mutableListOf<Node>()
        if (!matchPunctuation("]")) {
          while (true) {
            elements.add(parseExpression())
            if (matchPunctuation(",")) continue
            expectPunctuation("]")
            break
          }
        }
        Node.ArrayLiteral(elements)
      }
      matchPunctuation("{") -> parseObjectLiteral()
      else -> throw ExpressionSyntaxException("Unexpected '${token.text}'", token.start, source)
    }
  }

  private fun parseObjectLiteral(): Node {
    val entries = mutableListOf<Pair<Node, Node>>()
    if (matchPunctuation("}")) return Node.ObjectLiteral(entries)
    while (true) {
      val keyToken = peek()
      val key =
        when (keyToken.type) {
          // An unquoted key is a name, not an identifier reference.
          TokenType.IDENTIFIER -> {
            advance()
            Node.Literal(VegaValue.Str(keyToken.text))
          }
          TokenType.STRING -> {
            advance()
            Node.Literal(VegaValue.Str(keyToken.text))
          }
          TokenType.NUMBER -> {
            advance()
            Node.Literal(VegaValue.Str(keyToken.text))
          }
          else -> throw ExpressionSyntaxException("Expected an object key", keyToken.start, source)
        }
      expectPunctuation(":")
      entries.add(key to parseExpression())
      if (matchPunctuation(",")) continue
      expectPunctuation("}")
      return Node.ObjectLiteral(entries)
    }
  }

  private fun parseNumber(token: Token): Double {
    val text = token.text
    return when {
      text.startsWith("0x") || text.startsWith("0X") ->
        text.substring(2).toLongOrNull(16)?.toDouble()
          ?: throw ExpressionSyntaxException("Invalid hex literal '$text'", token.start, source)
      text.startsWith("0b") || text.startsWith("0B") ->
        text.substring(2).toLongOrNull(2)?.toDouble()
          ?: throw ExpressionSyntaxException("Invalid binary literal '$text'", token.start, source)
      else ->
        text.toDoubleOrNull()
          ?: throw ExpressionSyntaxException("Invalid number '$text'", token.start, source)
    }
  }

  // ---- token helpers --------------------------------------------------------

  private fun peek(): Token = tokens[position]

  private fun advance(): Token = tokens[position++]

  private fun matchOperator(text: String): Boolean {
    val token = peek()
    if (token.type == TokenType.OPERATOR && token.text == text) {
      advance()
      return true
    }
    return false
  }

  private fun matchPunctuation(text: String): Boolean {
    val token = peek()
    if (token.type == TokenType.PUNCTUATION && token.text == text) {
      advance()
      return true
    }
    return false
  }

  private fun expectPunctuation(text: String) {
    val token = peek()
    if (token.type != TokenType.PUNCTUATION || token.text != text) {
      throw ExpressionSyntaxException(
        "Expected '$text' but found '${token.text}'",
        token.start,
        source,
      )
    }
    advance()
  }

  private companion object {
    val UNARY_OPERATORS = setOf("+", "-", "!", "~")

    /**
     * JavaScript binary precedence, lowest binds loosest.
     *
     * Reproduced from the language rather than invented: `|` really does bind looser than `^`,
     * which binds looser than `&`, and all three looser than equality — a grouping most people
     * would guess wrong.
     */
    val PRECEDENCE: Map<String, Int> =
      mapOf(
        "||" to 1,
        "&&" to 2,
        "|" to 3,
        "^" to 4,
        "&" to 5,
        "==" to 6,
        "!=" to 6,
        "===" to 6,
        "!==" to 6,
        "<" to 7,
        "<=" to 7,
        ">" to 7,
        ">=" to 7,
        "<<" to 8,
        ">>" to 8,
        ">>>" to 8,
        "+" to 9,
        "-" to 9,
        "*" to 10,
        "/" to 10,
        "%" to 10,
      )
  }
}
