package dev.aster.vega.expression

import dev.aster.vega.model.VegaValue
import io.github.mgilbir.ecma262.number.toEcmaDouble

/**
 * Recursive-descent parser with a precedence table, for Vega's expression language.
 *
 * Precedence and associativity follow JavaScript's, because Vega's own implementation compiles
 * expressions to JavaScript and inherits them. Getting this wrong is quietly catastrophic: `a + b *
 * c` would evaluate as `(a + b) * c` and the chart would simply be wrong, with nothing to indicate
 * why.
 *
 * No `eval`, no reflection, no generated bytecode — the result is a plain tree that [Evaluator]
 * walks.
 */
public class Parser(private val source: String) {

  private val tokens = Lexer(source).tokenize()
  private var position = 0

  /**
   * How deep the recursion is, and how deep it may go.
   *
   * A recursive-descent parser recurses once per level of nesting, so `"((((…"` a few thousand deep
   * is a `StackOverflowError` — which is an `Error` rather than an exception, is not caught by
   * anything typed, and is **unrecoverable on Kotlin/Native**. An expression is data, so the depth
   * is counted and refused with the same syntax error every other malformed expression gets.
   *
   * 256 is far past anything a person or a compiler writes: the deepest expression in the whole
   * fixture corpus nests eight levels, and Vega-Lite's generated predicates reach about twenty.
   */
  private var depth = 0

  private inline fun <T> nested(block: () -> T): T {
    if (++depth > MAX_DEPTH) {
      depth = 0
      throw ExpressionSyntaxException(
        "Nested more than $MAX_DEPTH levels deep",
        peek().start,
        source,
      )
    }
    try {
      return block()
    } finally {
      depth--
    }
  }

  public fun parse(): Node {
    val node = parseExpression()
    val token = peek()
    if (token.type != TokenType.END) {
      throw ExpressionSyntaxException("Unexpected '${token.text}'", token.start, source)
    }
    return node
  }

  // ---- precedence climbing --------------------------------------------------

  private fun parseExpression(): Node = nested { parseConditional() }

  /** `test ? consequent : alternate`, right-associative. */
  private fun parseConditional(): Node {
    val test = parseBinary(0)
    if (!matchOperator("?")) return test
    val consequent = parseExpression()
    expectPunctuation(":")
    val alternate = parseExpression()
    return Node.Conditional(test, consequent, alternate)
  }

  /**
   * Left-associative binary operators, climbing the precedence table.
   *
   * `&&` and `||` become [Node.Logical] rather than [Node.Binary] because they short-circuit, and
   * the evaluator has to know not to evaluate the right operand.
   */
  private fun parseBinary(minimumPrecedence: Int): Node {
    var left = parseUnary()
    while (true) {
      val token = peek()
      if (token.type != TokenType.OPERATOR) return left
      val precedence = PRECEDENCE[token.text] ?: return left
      if (precedence < minimumPrecedence) return left
      advance()
      val right = parseBinary(precedence + 1)
      left =
        if (token.text == "&&" || token.text == "||") Node.Logical(token.text, left, right)
        else Node.Binary(token.text, left, right)
    }
  }

  private fun parseUnary(): Node {
    val token = peek()
    if (token.type == TokenType.OPERATOR && token.text in UNARY_OPERATORS) {
      advance()
      // Counted too: `!!!!…` recurses here without ever passing through `parseExpression`.
      return nested { Node.Unary(token.text, parseUnary()) }
    }
    return parsePostfix()
  }

  /** Member access and calls, which bind tighter than any operator and chain left to right. */
  private fun parsePostfix(): Node {
    var node = parsePrimary()
    while (true) {
      node =
        when {
          matchPunctuation(".") -> {
            val name = peek()
            if (name.type != TokenType.IDENTIFIER) {
              throw ExpressionSyntaxException("Expected a property name", name.start, source)
            }
            advance()
            Node.Member(node, Node.Identifier(name.text), computed = false)
          }
          matchPunctuation("[") -> {
            val property = parseExpression()
            expectPunctuation("]")
            Node.Member(node, property, computed = true)
          }
          matchPunctuation("(") -> Node.Call(node, parseArguments())
          else -> return node
        }
    }
  }

  private fun parseArguments(): List<Node> {
    val arguments = mutableListOf<Node>()
    if (matchPunctuation(")")) return arguments
    while (true) {
      arguments.add(parseExpression())
      if (matchPunctuation(",")) continue
      expectPunctuation(")")
      return arguments
    }
  }

  private fun parsePrimary(): Node {
    val token = peek()
    return when {
      token.type == TokenType.NUMBER -> {
        advance()
        Node.Literal(VegaValue.Num(parseNumber(token)))
      }
      token.type == TokenType.STRING -> {
        advance()
        Node.Literal(VegaValue.Str(token.text))
      }
      token.type == TokenType.REGEX -> {
        advance()
        Node.Literal(pattern(token))
      }
      token.type == TokenType.IDENTIFIER ->
        when (token.text) {
          "true" -> {
            advance()
            Node.Literal(VegaValue.Bool(true))
          }
          "false" -> {
            advance()
            Node.Literal(VegaValue.Bool(false))
          }
          "null" -> {
            advance()
            Node.Literal(VegaValue.Null)
          }
          else -> {
            advance()
            Node.Identifier(token.text)
          }
        }
      matchPunctuation("(") -> {
        val inner = parseExpression()
        expectPunctuation(")")
        inner
      }
      matchPunctuation("[") -> {
        val elements = mutableListOf<Node>()
        if (!matchPunctuation("]")) {
          while (true) {
            elements.add(parseExpression())
            if (matchPunctuation(",")) continue
            expectPunctuation("]")
            break
          }
        }
        Node.ArrayLiteral(elements)
      }
      matchPunctuation("{") -> parseObjectLiteral()
      else -> throw ExpressionSyntaxException("Unexpected '${token.text}'", token.start, source)
    }
  }

  private fun parseObjectLiteral(): Node {
    val entries = mutableListOf<Pair<Node, Node>>()
    if (matchPunctuation("}")) return Node.ObjectLiteral(entries)
    while (true) {
      val keyToken = peek()
      val key =
        when (keyToken.type) {
          // An unquoted key is a name, not an identifier reference.
          TokenType.IDENTIFIER -> {
            advance()
            Node.Literal(VegaValue.Str(keyToken.text))
          }
          TokenType.STRING -> {
            advance()
            Node.Literal(VegaValue.Str(keyToken.text))
          }
          TokenType.NUMBER -> {
            advance()
            Node.Literal(VegaValue.Str(keyToken.text))
          }
          else -> throw ExpressionSyntaxException("Expected an object key", keyToken.start, source)
        }
      expectPunctuation(":")
      entries.add(key to parseExpression())
      if (matchPunctuation(",")) continue
      expectPunctuation("}")
      return Node.ObjectLiteral(entries)
    }
  }

  /**
   * A `/pattern/flags` token, compiled to the same [VegaValue.Pattern] that `regexp()` produces.
   *
   * The literal and the function reach one representation deliberately: `test`, `replace` and the
   * rest already accept a `Pattern`, and `isRegExp` already answers true for one, so a literal is a
   * second *spelling* rather than a second kind of value. Nothing downstream needs to know which
   * was written.
   *
   * **Compiled here, not in the lexer.** The pattern is validated by `ktecma262`, the engine that
   * will run it, so an unreadable pattern is refused by the thing whose opinion counts rather than
   * by a second grammar this file would have to keep in step with it. It is a *syntax* error
   * because a literal is source text: `/[/` cannot be evaluated later, it can only fail to parse,
   * and the offset points at the delimiter so a reader can see which literal.
   *
   * The closing delimiter is the last `/` in the token, which is unambiguous because flags are
   * letters — see [TokenType.REGEX].
   */
  private fun pattern(token: Token): VegaValue.Pattern {
    val close = token.text.lastIndexOf('/')
    val source = token.text.substring(1, close)
    val flags = token.text.substring(close + 1)
    return try {
      VegaValue.Pattern(source, flags)
    } catch (failure: Exception) {
      throw ExpressionSyntaxException(
        "Invalid regular expression" + (failure.message?.let { ": $it" } ?: ""),
        token.start,
        this.source,
      )
    }
  }

  /**
   * A numeric literal, read by ECMA-262's rules rather than by the platform's.
   *
   * This used Kotlin's `toDoubleOrNull` and `toLongOrNull(16)`, and the two disagree with
   * JavaScript in both directions (#155). `toLongOrNull(16)` overflows to null past 64 bits, so
   * `0xFFFFFFFFFFFFFFFFFF` — an ordinary double in a browser, at 4.72e21 — was a **syntax error**
   * here, and hex literals are exactly what colour arithmetic is written with. In the other
   * direction Kotlin accepts `1d`, `1f` and `0x1p3`, none of which is a JavaScript number.
   *
   * `toEcmaDouble` is the specification's `StringNumericLiteral`, so `0o17` is 15 and the wide hex
   * literal is the double a browser gives. A literal it cannot read answers `NaN`, which stays a
   * syntax error here rather than becoming a silent `NaN` in a chart.
   */
  private fun parseNumber(token: Token): Double {
    val value = token.text.toEcmaDouble()
    if (value.isNaN()) {
      throw ExpressionSyntaxException("Invalid number '${token.text}'", token.start, source)
    }
    return value
  }

  // ---- token helpers --------------------------------------------------------

  private fun peek(): Token = tokens[position]

  private fun advance(): Token = tokens[position++]

  private fun matchOperator(text: String): Boolean {
    val token = peek()
    if (token.type == TokenType.OPERATOR && token.text == text) {
      advance()
      return true
    }
    return false
  }

  private fun matchPunctuation(text: String): Boolean {
    val token = peek()
    if (token.type == TokenType.PUNCTUATION && token.text == text) {
      advance()
      return true
    }
    return false
  }

  private fun expectPunctuation(text: String) {
    val token = peek()
    if (token.type != TokenType.PUNCTUATION || token.text != text) {
      throw ExpressionSyntaxException(
        "Expected '$text' but found '${token.text}'",
        token.start,
        source,
      )
    }
    advance()
  }

  private companion object {
    val UNARY_OPERATORS = setOf("+", "-", "!", "~")

    /**
     * JavaScript binary precedence, lowest binds loosest.
     *
     * Reproduced from the language rather than invented: `|` really does bind looser than `^`,
     * which binds looser than `&`, and all three looser than equality — a grouping most people
     * would guess wrong.
     */
    val PRECEDENCE: Map<String, Int> =
      mapOf(
        "||" to 1,
        "&&" to 2,
        "|" to 3,
        "^" to 4,
        "&" to 5,
        "==" to 6,
        "!=" to 6,
        "===" to 6,
        "!==" to 6,
        "<" to 7,
        "<=" to 7,
        ">" to 7,
        ">=" to 7,
        "<<" to 8,
        ">>" to 8,
        ">>>" to 8,
        "+" to 9,
        "-" to 9,
        "*" to 10,
        "/" to 10,
        "%" to 10,
      )
  }
}

/** See `Parser.depth`. */
private const val MAX_DEPTH: Int = 256
