package dev.aster.vegalite

import dev.aster.vega.model.DiagnosticSeverity
import dev.aster.vega.model.VegaJson
import dev.aster.vega.model.VegaValue
import dev.aster.vega.model.locale.VegaLocale
import java.io.File
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.MethodSource

/**
 * The gate for the Vega-Lite compiler: every fixture compiled here, and compared with what upstream
 * Vega-Lite compiles the same fixture into.
 *
 * This compares the *specification*, not a picture of it, and that is deliberate. Vega-Lite's whole
 * value is in the defaults it supplies — a scale type, a stack transform, a tick count, a label
 * angle — and each of those is one property of the output. Comparing the emitted Vega names the
 * rule that drifted; comparing only the rendered chart would say "some marks moved".
 *
 * The rendered chart is checked too, by [VegaLiteRenderTest], because a specification can be right
 * property by property and still not be the one upstream drew.
 *
 * Fixtures are discovered from the directory, so adding one is a file plus its references,
 * generated by `scripts/vega-lite-oracle.sh`.
 */
class VegaLiteFixtureTest {

  @ParameterizedTest(name = "{0}")
  @MethodSource("fixtures")
  fun `compiles without errors`(name: String) {
    val compiled = compile(name)
    val serious = compiled.diagnostics.filter { it.severity >= DiagnosticSeverity.ERROR }
    assertTrue(
      serious.isEmpty(),
      "$name should compile cleanly; got:\n${serious.joinToString("\n")}",
    )
    assertTrue(compiled.isUsable, "$name produced no specification")
  }

  @ParameterizedTest(name = "{0}")
  @MethodSource("fixtures")
  fun `emits the Vega upstream emits`(name: String) {
    val compiled = requireNotNull(compile(name).vega) { "$name produced no specification" }
    val expected = VegaJson.parse(reference(name, "vega").readText())
    val differences = SpecDiff.compare(expected, compiled)
    assertTrue(
      differences.isEmpty(),
      buildString {
        append("$name: ${differences.size} difference(s) from upstream's compiler\n")
        differences.take(40).forEach { append("  ").append(it).append('\n') }
        if (differences.size > 40) append("  ... ${differences.size - 40} more\n")
      },
    )
  }

  @ParameterizedTest(name = "{0}")
  @MethodSource("fixtures")
  fun `compilation is deterministic`(name: String) {
    val text = specFile(name).readText()
    val once = VegaLiteCompiler().compileJson(text).toJson()
    val again = VegaLiteCompiler().compileJson(text).toJson()
    assertEquals(once, again, name)
  }

  @Test
  fun `a specification with no mark is refused by name`() {
    val compiled = VegaLiteCompiler().compileJson("""{"data": {"values": [{"a": 1}]}}""")
    assertTrue(
      compiled.diagnostics.any { it.code == VegaLiteDiagnostics.MISSING_MARK },
      "a missing mark should be reported by name, got ${compiled.diagnostics}",
    )
  }

  @Test
  fun `an unimplemented composition is refused by name rather than approximated`() {
    // A composition **inside a layer**. This assertion has been repointed twice as the compositions
    // it named were implemented, so it is now pointed at one that cannot be: a layer draws its
    // members over one another, so each is a view or a layer of views, and upstream throws while
    // normalising rather than compiling it. There is no chart here to reach later.
    val compiled =
      VegaLiteCompiler()
        .compileJson(
          """
          {
            "data": {"values": [{"a": "p", "x": 1}]},
            "layer": [
              {"hconcat": [{"mark": "point", "encoding": {"x": {"field": "x", "type": "quantitative"}}}]}
            ]
          }
          """
            .trimIndent()
        )
    val reported =
      compiled.diagnostics.filter { it.code == VegaLiteDiagnostics.UNSUPPORTED_COMPOSITION }
    assertTrue(
      reported.isNotEmpty(),
      "the composition inside a layer should be reported, got ${compiled.diagnostics}",
    )
    assertTrue(
      reported.first().message.contains("hconcat"),
      "the report should name the construct: ${reported.first().message}",
    )
  }

  @Test
  fun `a facet inside a facet compiles rather than being refused`() {
    // The counterpart of the refusal above, and worth asserting separately: what used to be
    // reported by name now draws. Two levels of cell group, the inner one holding the marks — so
    // the innermost cell is named one `child` deeper than a single grid's.
    val compiled =
      VegaLiteCompiler()
        .compileJson(
          """
          {
            "data": {"values": [{"a": 1, "b": 2}]},
            "facet": {"column": {"field": "a"}},
            "spec": {
              "facet": {"row": {"field": "b"}},
              "spec": {"mark": "bar", "encoding": {"x": {"field": "a", "type": "quantitative"}}}
            }
          }
          """
            .trimIndent()
        )
    assertTrue(
      compiled.diagnostics.none { it.code == VegaLiteDiagnostics.UNSUPPORTED_COMPOSITION },
      "a nested grid should compile, got ${compiled.diagnostics}",
    )
    val vega = requireNotNull(compiled.toJson()) { "no Vega specification" }
    assertTrue(vega.contains("child_child_width"), "the innermost cell is two levels deep")
    assertTrue(vega.contains("child_cell"), "the inner cell group")
  }

  @Test
  fun `a composition a grid cannot hold is reported rather than dropped`() {
    // A concatenation inside a grid compiles now; a **grid inside that concatenation** does not,
    // and
    // this is the assertion that it says so. Both of the compositions this test has named produced
    // a
    // plausible chart measuring the wrong rows before they were caught — which is the failure this
    // repository least wants, and the reason the assertion is on the report and not the refusal.
    val compiled =
      VegaLiteCompiler()
        .compileJson(
          """
          {
            "data": {"values": [{"a": "p", "b": "q", "x": 1}]},
            "facet": {"column": {"field": "a"}},
            "spec": {
              "hconcat": [
                {
                  "facet": {"row": {"field": "b"}},
                  "spec": {
                    "mark": "point",
                    "encoding": {"x": {"field": "x", "type": "quantitative"}}
                  }
                }
              ]
            }
          }
          """
            .trimIndent()
        )
    assertNull(compiled.toJson(), "a chart that cannot be compiled should produce nothing")
    val reported =
      compiled.diagnostics.filter { it.code == VegaLiteDiagnostics.UNSUPPORTED_COMPOSITION }
    assertTrue(reported.isNotEmpty(), "it should be reported, got ${compiled.diagnostics}")
    assertTrue(
      reported.first().message.contains("facet"),
      "and the report should name the composition: ${reported.first().message}",
    )
  }

  @Test
  fun `a composition inside a layer names the composition and not a missing mark`() {
    // It was reported as a **missing mark**, which named the symptom: a `facet` has no `mark` of
    // its
    // own, so the first thing to fail was the innermost check. That sent the reader looking for a
    // mark in a specification whose trouble was the composition around it.
    val compiled =
      VegaLiteCompiler()
        .compileJson(
          """
          {
            "data": {"values": [{"a": "p", "x": 1}]},
            "layer": [
              {
                "facet": {"column": {"field": "a"}},
                "spec": {
                  "mark": "point",
                  "encoding": {"x": {"field": "x", "type": "quantitative"}}
                }
              }
            ]
          }
          """
            .trimIndent()
        )
    val reported =
      compiled.diagnostics.filter { it.code == VegaLiteDiagnostics.UNSUPPORTED_COMPOSITION }
    assertTrue(reported.isNotEmpty(), "it should be reported, got ${compiled.diagnostics}")
    assertTrue(
      reported.first().message.contains("facet") && reported.first().message.contains("layer"),
      "naming both sides of it: ${reported.first().message}",
    )
    assertTrue(
      compiled.diagnostics.none { it.code == VegaLiteDiagnostics.MISSING_MARK },
      "and not as a missing mark: ${compiled.diagnostics}",
    )
  }

  @Test
  fun `a facet inside a facet compiles inside a concatenation too`() {
    // The levels belong to the plot that wrote them, so everything the nest publishes runs through
    // that plot's own name rather than the chart's.
    val compiled =
      VegaLiteCompiler()
        .compileJson(
          """
          {
            "data": {"values": [{"a": 1, "b": 2}]},
            "hconcat": [
              {
                "facet": {"column": {"field": "a"}},
                "spec": {
                  "facet": {"row": {"field": "b"}},
                  "spec": {
                    "mark": "bar",
                    "encoding": {"x": {"field": "a", "type": "quantitative"}}
                  }
                }
              }
            ]
          }
          """
            .trimIndent()
        )
    assertTrue(
      compiled.diagnostics.none { it.code == VegaLiteDiagnostics.UNSUPPORTED_COMPOSITION },
      "a nested grid in a concatenation should compile, got ${compiled.diagnostics}",
    )
    val vega = requireNotNull(compiled.toJson()) { "no Vega specification" }
    assertTrue(vega.contains("concat_0_child_cell"), "the inner cell is the plot's own")
    assertTrue(vega.contains("concat_0_child_child_width"), "and so is its cell's size")
  }

  companion object {
    private val repositoryRoot: File = File(System.getProperty("user.dir")).parentFile

    private fun specFile(name: String) =
      File(repositoryRoot, "test-fixtures/vega-lite/$name.vl.json")

    private fun reference(name: String, kind: String) =
      File(repositoryRoot, "test-fixtures/vega-lite-reference/$name.$kind.json")

    /**
     * The locale upstream's own tests assume, **named** rather than defaulted.
     *
     * Every fixture here is compared against what upstream's compiler emitted, and since a locale
     * now decides the order of a date's fields, the locale a fixture compiles under is part of what
     * is being compared. `VegaLocale.EnglishUS` is the only one that states its specifier table
     * instead of deriving one from its own `%x`, and it states upstream's — so naming it here is
     * what makes these 283 comparisons a statement about the compiler rather than about a default
     * parameter.
     */
    fun compile(name: String): VegaLiteCompilation =
      VegaLiteCompiler(locale = VegaLocale.EnglishUS).compileJson(specFile(name).readText())

    fun referenceSpec(name: String): VegaValue = VegaJson.parse(reference(name, "vega").readText())

    fun sceneReference(name: String): File = reference(name, "reference")

    @JvmStatic
    fun fixtures(): List<String> =
      requireNotNull(File(repositoryRoot, "test-fixtures/vega-lite").listFiles()) {
          "no Vega-Lite fixture directory"
        }
        .filter { it.name.endsWith(".vl.json") }
        .map { it.name.removeSuffix(".vl.json") }
        .sorted()
        .also { require(it.isNotEmpty()) { "no Vega-Lite fixtures found" } }
  }
}
