package dev.aster.vegalite

import dev.aster.vega.model.DiagnosticSeverity
import dev.aster.vega.model.VegaJson
import dev.aster.vega.model.VegaValue
import java.io.File
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.MethodSource

/**
 * The gate for the Vega-Lite compiler: every fixture compiled here, and compared with what upstream
 * Vega-Lite compiles the same fixture into.
 *
 * This compares the *specification*, not a picture of it, and that is deliberate. Vega-Lite's whole
 * value is in the defaults it supplies — a scale type, a stack transform, a tick count, a label
 * angle — and each of those is one property of the output. Comparing the emitted Vega names the
 * rule that drifted; comparing only the rendered chart would say "some marks moved".
 *
 * The rendered chart is checked too, by [VegaLiteRenderTest], because a specification can be right
 * property by property and still not be the one upstream drew.
 *
 * Fixtures are discovered from the directory, so adding one is a file plus its references,
 * generated by `scripts/vega-lite-oracle.sh`.
 */
class VegaLiteFixtureTest {

  @ParameterizedTest(name = "{0}")
  @MethodSource("fixtures")
  fun `compiles without errors`(name: String) {
    val compiled = compile(name)
    val serious = compiled.diagnostics.filter { it.severity >= DiagnosticSeverity.ERROR }
    assertTrue(
      serious.isEmpty(),
      "$name should compile cleanly; got:\n${serious.joinToString("\n")}",
    )
    assertTrue(compiled.isUsable, "$name produced no specification")
  }

  @ParameterizedTest(name = "{0}")
  @MethodSource("fixtures")
  fun `emits the Vega upstream emits`(name: String) {
    val compiled = requireNotNull(compile(name).vega) { "$name produced no specification" }
    val expected = VegaJson.parse(reference(name, "vega").readText())
    val differences = SpecDiff.compare(expected, compiled)
    assertTrue(
      differences.isEmpty(),
      buildString {
        append("$name: ${differences.size} difference(s) from upstream's compiler\n")
        differences.take(40).forEach { append("  ").append(it).append('\n') }
        if (differences.size > 40) append("  ... ${differences.size - 40} more\n")
      },
    )
  }

  @ParameterizedTest(name = "{0}")
  @MethodSource("fixtures")
  fun `compilation is deterministic`(name: String) {
    val text = specFile(name).readText()
    val once = VegaLiteCompiler().compileJson(text).toJson()
    val again = VegaLiteCompiler().compileJson(text).toJson()
    assertEquals(once, again, name)
  }

  @Test
  fun `a specification with no mark is refused by name`() {
    val compiled = VegaLiteCompiler().compileJson("""{"data": {"values": [{"a": 1}]}}""")
    assertTrue(
      compiled.diagnostics.any { it.code == VegaLiteDiagnostics.MISSING_MARK },
      "a missing mark should be reported by name, got ${compiled.diagnostics}",
    )
  }

  @Test
  fun `an unimplemented composition is refused by name rather than approximated`() {
    // A plot of a concatenation with its own dataset: the plots share the chart's, and a second
    // source would have to be assembled and numbered beside the first.
    val compiled =
      VegaLiteCompiler()
        .compileJson(
          """
          {
            "data": {"values": [{"a": 1}]},
            "hconcat": [
              {"mark": "bar", "encoding": {"x": {"field": "a", "type": "quantitative"}}},
              {"data": {"values": [{"b": 2}]}, "mark": "bar"}
            ]
          }
          """
            .trimIndent()
        )
    val reported =
      compiled.diagnostics.filter { it.code == VegaLiteDiagnostics.UNSUPPORTED_COMPOSITION }
    assertTrue(
      reported.isNotEmpty(),
      "the plot's own data should be reported, got ${compiled.diagnostics}",
    )
    assertTrue(
      reported.first().message.contains("data"),
      "the report should name the construct: ${reported.first().message}",
    )
  }

  companion object {
    private val repositoryRoot: File = File(System.getProperty("user.dir")).parentFile

    private fun specFile(name: String) =
      File(repositoryRoot, "test-fixtures/vega-lite/$name.vl.json")

    private fun reference(name: String, kind: String) =
      File(repositoryRoot, "test-fixtures/vega-lite-reference/$name.$kind.json")

    fun compile(name: String): VegaLiteCompilation =
      VegaLiteCompiler().compileJson(specFile(name).readText())

    fun referenceSpec(name: String): VegaValue = VegaJson.parse(reference(name, "vega").readText())

    fun sceneReference(name: String): File = reference(name, "reference")

    @JvmStatic
    fun fixtures(): List<String> =
      requireNotNull(File(repositoryRoot, "test-fixtures/vega-lite").listFiles()) {
          "no Vega-Lite fixture directory"
        }
        .filter { it.name.endsWith(".vl.json") }
        .map { it.name.removeSuffix(".vl.json") }
        .sorted()
        .also { require(it.isNotEmpty()) { "no Vega-Lite fixtures found" } }
  }
}
