package dev.aster.vega.expression

import dev.aster.vega.model.VegaValue
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.CsvSource

/**
 * Reference vectors for the expression engine, every one generated by evaluating the expression
 * with upstream Vega (`oracle-js/src/eval-probe.js`).
 *
 * The expected column is what Vega actually returns, serialized as JSON — so `NaN` and `Infinity`
 * appear as `null`, exactly as they do coming out of the oracle. These are not restatements of the
 * implementation: several of them contradicted a first, reasonable-looking implementation and were
 * the reason it changed.
 */
class ExpressionReferenceTest {

  private val compiler = VegaExpressionCompiler()

  /**
   * Evaluates and renders the result the way `JSON.stringify` would, for comparison with the
   * oracle.
   */
  private fun evaluate(source: String): String {
    val result = compiler.compile(source)
    assertTrue(result is ExpressionResult.Compiled, "failed to parse '$source': $result")
    val expression = (result as ExpressionResult.Compiled).expression
    return asJson(expression.evaluate(EmptyScope))
  }

  private fun asJson(value: VegaValue): String =
    when (value) {
      is VegaValue.Null -> "null"
      is VegaValue.Bool -> value.value.toString()
      // JSON has no NaN or Infinity, so JSON.stringify emits null; match that.
      is VegaValue.Num ->
        if (!value.value.isFinite()) "null" else JsSemantics.numberToString(value.value)
      is VegaValue.Timestamp -> JsSemantics.numberToString(value.epochMillis)
      is VegaValue.Str -> "\"${value.value}\""
      is VegaValue.Arr -> value.values.joinToString(",", "[", "]") { asJson(it) }
      is VegaValue.Obj ->
        value.fields.entries.joinToString(",", "{", "}") { "\"${it.key}\":${asJson(it.value)}" }
    }

  private object EmptyScope : ExpressionScope {
    override val datum: VegaValue = VegaValue.EmptyObject

    override fun signal(name: String): VegaValue = VegaValue.Null

    override fun dataset(name: String): List<VegaValue> = emptyList()
  }

  @ParameterizedTest(name = "{0} => {1}")
  @CsvSource(
    delimiter = '|',
    value =
      [
        // ---- arithmetic and precedence ----
        "1 + 2|3",
        "2 + 3 * 4|14",
        "(2 + 3) * 4|20",
        "2 - 3 - 4|-5",
        "2 * 3 % 4|2",
        "7 / 2|3.5",
        "7 % 3|1",
        "-7 % 3|-1",
        "1 / 0|null",
        "0 / 0|null",
        "true + true|2",
        // ---- string concatenation, the surprising operator ----
        "1 + \"2\"|\"12\"",
        "\"a\" + \"b\"|\"ab\"",
        "\"a\" + 1 + 2|\"a12\"",
        "1 + 2 + \"a\"|\"3a\"",
        "null + 1|1",
        "null + \"a\"|\"nulla\"",
        // An array primitivizes to a string for `+`, so this concatenates rather than adds.
        "[1] + 1|\"11\"",
        "[1,2] + \"\"|\"1,2\"",
        // ---- equality ----
        "1 == \"1\"|true",
        "1 === \"1\"|false",
        "\"\" == 0|true",
        "1 + 2 == 3|true",
        "1 < 2 == true|true",
        "!true == false|true",
        // ---- relational ----
        "1 < 2|true",
        "10 < 9|false",
        "\"a\" < \"b\"|true",
        // Both operands are strings, so this is lexicographic, not numeric.
        "\"10\" < \"9\"|true",
        // ---- logical, unary, bitwise ----
        "!0|true",
        "!\"\"|true",
        "!\"a\"|false",
        "-\"3\"|-3",
        "+\"3\"|3",
        "~5|-6",
        // Unary minus binds tighter than `^`, and `^` is XOR, not exponentiation.
        "-2 ^ 2|-4",
        "1 << 2 + 1|8",
        "8 >> 1 >> 1|2",
        "-1 >>> 28|15",
        "\"x\" && \"y\"|\"y\"",
        // ---- conditional ----
        "1 ? \"y\" : \"n\"|\"y\"",
        "0 ? \"y\" : \"n\"|\"n\"",
        "true ? 1 : 2 ? 3 : 4|1",
        "0 ? 1 : 0 ? 3 : 4|4",
        // ---- numeric coercion of strings ----
        "+\" 12 \"|12",
        "+\"1e3\"|1000",
        "+\"0x10\"|16",
        "+\"abc\"|null",
        // ---- members, literals, constants ----
        "[1,2,3][1]|2",
        "[1,2,3].length|3",
        "\"abc\".length|3",
        "\"abc\"[1]|\"b\"",
        "PI > 3|true",
        "E > 2|true",
        "sqrt(2) == SQRT2|true",
      ],
  )
  fun `matches upstream Vega`(source: String, expected: String) {
    assertEquals(expected, evaluate(source), "expression: $source")
  }

  @ParameterizedTest(name = "{0} => {1}")
  @CsvSource(
    delimiter = '|',
    value =
      [
        // ---- math ----
        "abs(-3)|3",
        "floor(2.7)|2",
        "ceil(2.1)|3",
        "sqrt(16)|4",
        "pow(2,10)|1024",
        "min(3,1,2)|1",
        "max(3,1,2)|3",
        "max(1)|1",
        // Vega's min/max are Math.min/Math.max: variadic, so an array argument is NaN, not a
        // reduction.
        "min([5,2,9])|null",
        "clamp(5,0,3)|3",
        // JavaScript rounds halves toward positive infinity.
        "round(0.5)|1",
        "round(-0.5)|0",
        "round(1.5)|2",
        "round(2.5)|3",
        "round(-2.5)|-2",
        // ---- predicates ----
        "isNumber(1)|true",
        "isString(\"a\")|true",
        "isArray([])|true",
        "isBoolean(true)|true",
        "isValid(null)|false",
        "isValid(1)|true",
        "isValid(0)|true",
        "isValid(\"\")|true",
        "isValid(NaN)|false",
        // ---- coercion ----
        "toNumber(\"42\")|42",
        "toString(42)|\"42\"",
        // Upstream returns null, not false, for the empty string.
        "toBoolean(\"\")|null",
        "toBoolean(0)|false",
        "toBoolean(\"x\")|true",
        "parseInt(\"42px\")|42",
        "parseFloat(\"3.5rem\")|3.5",
        "parseInt(\"ff\",16)|255",
        // ---- strings ----
        "upper(\"ab\")|\"AB\"",
        "lower(\"AB\")|\"ab\"",
        "substring(\"hello\",1,3)|\"el\"",
        "indexof(\"hello\",\"l\")|2",
        "lastindexof(\"abcabc\",\"b\")|4",
        "replace(\"a-b\",\"-\",\"+\")|\"a+b\"",
        "pad(\"5\",3,\"0\",\"left\")|\"005\"",
        "lower(\"ABC\") + upper(\"de\")|\"abcDE\"",
        // ---- arrays ----
        "length([1,2,3])|3",
        "join([\"a\",\"b\"],\"-\")|\"a-b\"",
        "indexof([1,2,3],2)|1",
        "span([3,7])|4",
        "peek([1,2,3])|3",
        "inrange(5,[0,10])|true",
        // ---- control flow ----
        "if(true,\"a\",\"b\")|\"a\"",
        "if(false,\"a\",\"b\")|\"b\"",
        // ---- formatting ----
        "format(1234.5678,\".2f\")|\"1234.57\"",
        "format(0.1234,\".1%\")|\"12.3%\"",
        "format(1234567,\",d\")|\"1,234,567\"",
      ],
  )
  fun `functions match upstream Vega`(source: String, expected: String) {
    assertEquals(expected, evaluate(source), "expression: $source")
  }

  @Test
  fun `array and object results match upstream`() {
    assertEquals("[\"a\",\"b\",\"c\"]", evaluate("split(\"a,b,c\",\",\")"))
    assertEquals("[3,2,1]", evaluate("reverse([1,2,3])"))
    assertEquals("[2,3]", evaluate("slice([1,2,3,4],1,3)"))
    assertEquals("[3,4]", evaluate("slice([1,2,3,4],-2)"))
    assertEquals("[1,5]", evaluate("clampRange([1,5],0,10)"))
    assertEquals("[0,10]", evaluate("clampRange([-5,5],0,10)"))
    assertEquals("[0,10]", evaluate("clampRange([0,20],0,10)"))
    assertEquals("\"abcd…\"", evaluate("truncate(\"abcdefgh\",5)"))
  }

  @Test
  fun `operators containing the csv delimiter match upstream`() {
    // These cannot live in the CSV table: `|` and `||` are the table's own delimiter, and an empty
    // string literal does not survive CSV quoting.
    assertEquals("3", evaluate("1 | 2 ^ 3 & 4"))
    // `||` reads as two delimiters in the CSV table, so it lives here too.
    assertEquals("\"fallback\"", evaluate("\"\" || \"fallback\""))
    assertEquals("\"x\"", evaluate("\"x\" || \"y\""))
    assertEquals("0", evaluate("+\"\""))
    assertEquals("0", evaluate("toNumber(\"\")"))
  }

  @Test
  fun `object literals support both quoted and bare keys`() {
    assertEquals("1", evaluate("{\"a\": 1}.a"))
    assertEquals("1", evaluate("{a: 1}[\"a\"]"))
  }

  /**
   * Date functions, pinned against upstream.
   *
   * Only the `utc` half is checked here, deliberately: the local-time half reads whatever zone the
   * machine is in, so a reference vector for it would pass in one place and fail in another. The
   * two share every line of implementation past the zone they are handed, and `TimeScaleTest`
   * covers the zone-dependent behaviour with zones it names explicitly.
   */
  @ParameterizedTest(name = "{0}")
  @CsvSource(
    delimiter = '|',
    value =
      [
        // ---- accessors: month and day-of-week are zero-based, quarter and day-of-year are not
        // ----
        "utcyear(utc(2026, 2, 14))|2026",
        "utcquarter(utc(2026, 2, 14))|1",
        "utcmonth(utc(2026, 2, 14))|2",
        "utcdate(utc(2026, 2, 14))|14",
        "utcday(utc(2026, 2, 14))|6",
        "utcdayofyear(utc(2026, 2, 14))|73",
        "utchours(utc(2026, 2, 14, 9, 5, 3, 250))|9",
        "utcminutes(utc(2026, 2, 14, 9, 5, 3, 250))|5",
        "utcseconds(utc(2026, 2, 14, 9, 5, 3, 250))|3",
        "utcmilliseconds(utc(2026, 2, 14, 9, 5, 3, 250))|250",
        // ---- construction rolls over, as JavaScript's Date does ----
        "utc(2026, 12, 1)|1798761600000",
        "utc(2026, 0, 32)|1769904000000",
        "utc(2026, 0, 1) - utc(2025, 11, 31)|86400000",
        "time(utc(2026, 0, 1))|1767225600000",
        // ---- formatting ----
        "utcFormat(utc(2026, 2, 14, 9, 5), '%Y-%m-%d %H:%M')|\"2026-03-14 09:05\"",
        "utcFormat(utc(2026, 0, 5), '%B %d, %Y')|\"January 05, 2026\"",
        "utcFormat(utc(2026, 0, 5), '%a %b %e')|\"Mon Jan  5\"",
        "utcFormat(utc(2026, 0, 5), '%j')|\"005\"",
        "utcFormat(utc(2026, 6, 4, 13, 7), '%I:%M %p')|\"01:07 PM\"",
        "utcFormat(utc(2026, 6, 4), '%y')|\"26\"",
        // ---- reading ----
        "toDate('2026-01-05T00:00:00Z')|1767571200000",
        "utcyear(toDate('2026-01-05T00:00:00Z'))|2026",
        "utcyear(1767225600000)|2026",
      ],
  )
  fun `date functions match upstream`(expression: String, expected: String) {
    assertEquals(expected, evaluate(expression), expression)
  }
}
