package dev.aster.vega.expression

import dev.aster.vega.model.VegaValue
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.CsvSource

/**
 * Reference vectors for the expression engine, every one generated by evaluating the expression
 * with upstream Vega (`oracle-js/src/eval-probe.js`).
 *
 * The expected column is what Vega actually returns, serialized as JSON — so `NaN` and `Infinity`
 * appear as `null`, exactly as they do coming out of the oracle. These are not restatements of the
 * implementation: several of them contradicted a first, reasonable-looking implementation and were
 * the reason it changed.
 */
class ExpressionReferenceTest {

  private val compiler = VegaExpressionCompiler()

  /**
   * Evaluates and renders the result the way `JSON.stringify` would, for comparison with the
   * oracle.
   */
  private fun evaluate(source: String): String {
    val result = compiler.compile(source)
    assertTrue(result is ExpressionResult.Compiled, "failed to parse '$source': $result")
    val expression = (result as ExpressionResult.Compiled).expression
    return asJson(expression.evaluate(EmptyScope))
  }

  private fun asJson(value: VegaValue): String =
    when (value) {
      is VegaValue.Null -> "null"
      // `eval-probe.js` writes the literal `undefined` where `JSON.stringify` gives nothing.
      is VegaValue.Undefined -> "undefined"
      is VegaValue.Bool -> value.value.toString()
      // JSON has no NaN or Infinity, so JSON.stringify emits null; match that.
      is VegaValue.Num ->
        if (!value.value.isFinite()) "null" else JsSemantics.numberToString(value.value)
      is VegaValue.Timestamp -> JsSemantics.numberToString(value.epochMillis)
      is VegaValue.Str -> "\"${value.value}\""
      is VegaValue.Arr -> value.values.joinToString(",", "[", "]") { asJson(it) }
      is VegaValue.Obj ->
        value.fields.entries.joinToString(",", "{", "}") { "\"${it.key}\":${asJson(it.value)}" }
      // `JSON.stringify(/a/)` is `{}` — a RegExp has no enumerable properties.
      is VegaValue.Pattern -> "{}"
    }

  /**
   * Every function upstream has either works or says why not.
   *
   * The list is upstream's own `functionContext`, read out of the pinned build:
   * ```
   * node --input-type=module -e "import * as vf from 'vega-functions';
   *   console.log(Object.keys(vf.functionContext).sort().join(' '))"
   * ```
   *
   * Nineteen of these had neither an implementation nor an entry in `knownUnsupported`, so an
   * expression using one got "unknown function" and no hint that the reason was a browser, a
   * running view or a value model that cannot hold a function. Sixteen more were simply missing and
   * are now implemented. A function upstream adds later shows up here as a failure, which is the
   * point.
   *
   * The five names not in the list below are resolved against the scope rather than this table —
   * `scale`, `data`, `domain`, `bandwidth` and their kin live where the scales and datasets are.
   */
  @Test
  fun `every upstream expression function is implemented or explained`() {
    val upstream =
      listOf(
        "bandspace",
        "clampRange",
        "containerSize",
        "contrast",
        "copy",
        "cumulativeLogNormal",
        "cumulativeNormal",
        "cumulativeUniform",
        "dayAbbrevFormat",
        "dayFormat",
        "dayofyear",
        "debug",
        "densityLogNormal",
        "densityNormal",
        "densityUniform",
        "encode",
        "extent",
        "flush",
        "format",
        "gradient",
        "hcl",
        "hsl",
        "inScope",
        "indexof",
        "info",
        "inrange",
        "intersect",
        "intersectLasso",
        "isArray",
        "isBoolean",
        "isDate",
        "isDefined",
        "isNumber",
        "isObject",
        "isRegExp",
        "isString",
        "isTuple",
        "isValid",
        "join",
        "lab",
        "lassoAppend",
        "lassoPath",
        "lastindexof",
        "lerp",
        "luminance",
        "merge",
        "modify",
        "monthAbbrevFormat",
        "monthFormat",
        "pad",
        "panLinear",
        "panLog",
        "panPow",
        "panSymlog",
        "pathShape",
        "peek",
        "pinchAngle",
        "pinchDistance",
        "pluck",
        "quantileLogNormal",
        "quantileNormal",
        "quantileUniform",
        "quarter",
        "replace",
        "reverse",
        "rgb",
        "screen",
        "sequence",
        "slice",
        "sort",
        "span",
        "timeFormat",
        "timeOffset",
        "timeParse",
        "timeSequence",
        "timeUnitSpecifier",
        "toBoolean",
        "toDate",
        "toNumber",
        "toString",
        "truncate",
        "utcFormat",
        "utcOffset",
        "utcParse",
        "utcSequence",
        "utcdayofyear",
        "utcquarter",
        "utcweek",
        "vlSelectionIdTest",
        "vlSelectionResolve",
        "vlSelectionTest",
        "vlSelectionTuples",
        "warn",
        "week",
        "windowSize",
        "zoomLinear",
        "zoomLog",
        "zoomPow",
        "zoomSymlog",
        "geoShape",
        "gradient",
      )
    // Resolved against the **scope** rather than through the function table, because each needs
    // something the table cannot see: the scales, the datasets, the projections, or somewhere to
    // send
    // a message. `Evaluator` dispatches these by name before it consults the table at all.
    val scopeBound =
      setOf(
        "scale",
        "invert",
        "domain",
        "range",
        "bandwidth",
        "data",
        "indata",
        "setdata",
        "treePath",
        "treeAncestors",
        "geoArea",
        "geoBounds",
        "geoCentroid",
        "geoScale",
        "geoShape",
        "gradient",
        "modify",
        "encode",
        "inScope",
        "intersect",
        "intersectLasso",
        "vlSelectionTest",
        "vlSelectionIdTest",
        "vlSelectionResolve",
        "vlSelectionTuples",
        "isTuple",
        "random",
        "sampleNormal",
        "sampleLogNormal",
        "sampleUniform",
        // The selection helpers read a **store** dataset, so they go through the scope as `data`
        // does rather than through the function table.
        "vlSelectionIdTest",
        "vlSelectionResolve",
        "vlSelectionTest",
        "warn",
        "info",
        "debug",
      )
    val unaccounted = upstream.filterNot {
      it in Functions.functions || it in Functions.knownUnsupported || it in scopeBound
    }
    assertEquals(emptyList<String>(), unaccounted)
  }

  private object EmptyScope : ExpressionScope {
    override val datum: VegaValue = VegaValue.EmptyObject

    override fun signal(name: String): VegaValue = VegaValue.Null

    override fun dataset(name: String): List<VegaValue> = emptyList()
  }

  @ParameterizedTest(name = "{0} => {1}")
  @CsvSource(
    delimiter = '|',
    value =
      [
        // ---- arithmetic and precedence ----
        "1 + 2|3",
        "2 + 3 * 4|14",
        "(2 + 3) * 4|20",
        "2 - 3 - 4|-5",
        "2 * 3 % 4|2",
        "7 / 2|3.5",
        "7 % 3|1",
        "-7 % 3|-1",
        "1 / 0|null",
        "0 / 0|null",
        "true + true|2",
        // ---- string concatenation, the surprising operator ----
        "1 + \"2\"|\"12\"",
        "\"a\" + \"b\"|\"ab\"",
        "\"a\" + 1 + 2|\"a12\"",
        "1 + 2 + \"a\"|\"3a\"",
        "null + 1|1",
        "null + \"a\"|\"nulla\"",
        // An array primitivizes to a string for `+`, so this concatenates rather than adds.
        "[1] + 1|\"11\"",
        "[1,2] + \"\"|\"1,2\"",
        // ---- equality ----
        "1 == \"1\"|true",
        "1 === \"1\"|false",
        "\"\" == 0|true",
        "1 + 2 == 3|true",
        "1 < 2 == true|true",
        "!true == false|true",
        // ---- relational ----
        "1 < 2|true",
        "10 < 9|false",
        "\"a\" < \"b\"|true",
        // Both operands are strings, so this is lexicographic, not numeric.
        "\"10\" < \"9\"|true",
        // ---- logical, unary, bitwise ----
        "!0|true",
        "!\"\"|true",
        "!\"a\"|false",
        "-\"3\"|-3",
        "+\"3\"|3",
        "~5|-6",
        // Unary minus binds tighter than `^`, and `^` is XOR, not exponentiation.
        "-2 ^ 2|-4",
        "1 << 2 + 1|8",
        "8 >> 1 >> 1|2",
        "-1 >>> 28|15",
        "\"x\" && \"y\"|\"y\"",
        // ---- conditional ----
        "1 ? \"y\" : \"n\"|\"y\"",
        "0 ? \"y\" : \"n\"|\"n\"",
        "true ? 1 : 2 ? 3 : 4|1",
        "0 ? 1 : 0 ? 3 : 4|4",
        // ---- numeric coercion of strings ----
        "+\" 12 \"|12",
        "+\"1e3\"|1000",
        "+\"0x10\"|16",
        "+\"abc\"|null",
        // ---- members, literals, constants ----
        "[1,2,3][1]|2",
        "[1,2,3].length|3",
        "\"abc\".length|3",
        "\"abc\"[1]|\"b\"",
        "PI > 3|true",
        "E > 2|true",
        "sqrt(2) == SQRT2|true",
      ],
  )
  fun `matches upstream Vega`(source: String, expected: String) {
    assertEquals(expected, evaluate(source), "expression: $source")
  }

  @ParameterizedTest(name = "{0} => {1}")
  @CsvSource(
    delimiter = '|',
    value =
      [
        // ---- regular expressions ----
        // The pair a text filter is written with. Every value here came off upstream: a pattern
        // stringifies to the literal a reader would have written, `test` takes a bare string as a
        // pattern because upstream compiles it to `RegExp(a).test(b)`, and only `g` makes `replace`
        // do more than the first match.
        "test(regexp('farmer','i'), 'Farmer')|true",
        "test(regexp('farmer'), 'Farmer')|false",
        "test('far', 'Farmer')|false",
        "test(regexp('^f','i'), 'Farmer')|true",
        "test(regexp('[0-9]+'), 'abc')|false",
        "test(regexp(''), 'anything')|true",
        "isRegExp(regexp('a'))|true",
        "isRegExp('a')|false",
        "'' + regexp('a.b','i')|\"/a.b/i\"",
        "length(regexp('abc') + '')|5",
        "replace('a-b-c', '-', '+')|\"a+b-c\"",
        "replace('a-b-c', regexp('-','g'), '+')|\"a+b+c\"",
        "replace('a-b-c', regexp('-'), '+')|\"a+b-c\"",
        "replace('Farmer', regexp('f','i'), 'F')|\"Farmer\"",
        // ---- math ----
        "abs(-3)|3",
        // `hypot` is variadic, not the two-argument function its name suggests, and with no
        // arguments it is zero.
        "hypot(3,4)|5",
        // `extent` compares the values as they are, so strings give lexicographic ends; null and
        // NaN are skipped, and an array with nothing usable in it gives two nulls.
        "extent([3,1,2])|[1,3]",
        "extent([])|[null,null]",
        "extent(['b','a','c'])|[\"a\",\"c\"]",
        "extent([1,null,5])|[1,5]",
        "extent([null])|[null,null]",
        "hypot()|0",
        "hypot(1)|1",
        "hypot(1,2,2)|3",
        "isFinite(hypot(-3,-4))|true",
        "floor(2.7)|2",
        "ceil(2.1)|3",
        "sqrt(16)|4",
        "pow(2,10)|1024",
        "min(3,1,2)|1",
        "max(3,1,2)|3",
        "max(1)|1",
        // Vega's min/max are Math.min/Math.max: variadic, so an array argument is NaN, not a
        // reduction.
        "min([5,2,9])|null",
        "clamp(5,0,3)|3",
        // JavaScript rounds halves toward positive infinity.
        "round(0.5)|1",
        "round(-0.5)|0",
        "round(1.5)|2",
        "round(2.5)|3",
        "round(-2.5)|-2",
        // ---- predicates ----
        "isNumber(1)|true",
        "isString(\"a\")|true",
        "isArray([])|true",
        "isBoolean(true)|true",
        "isValid(null)|false",
        "isValid(1)|true",
        "isValid(0)|true",
        "isValid(\"\")|true",
        "isValid(NaN)|false",
        // ---- coercion ----
        "toNumber(\"42\")|42",
        "toString(42)|\"42\"",
        // Upstream returns null, not false, for the empty string.
        "toBoolean(\"\")|null",
        "toBoolean(0)|false",
        "toBoolean(\"x\")|true",
        "parseInt(\"42px\")|42",
        "parseFloat(\"3.5rem\")|3.5",
        "parseInt(\"ff\",16)|255",
        // ---- strings ----
        "upper(\"ab\")|\"AB\"",
        "lower(\"AB\")|\"ab\"",
        "substring(\"hello\",1,3)|\"el\"",
        "indexof(\"hello\",\"l\")|2",
        "lastindexof(\"abcabc\",\"b\")|4",
        "replace(\"a-b\",\"-\",\"+\")|\"a+b\"",
        "pad(\"5\",3,\"0\",\"left\")|\"005\"",
        "lower(\"ABC\") + upper(\"de\")|\"abcDE\"",
        // ---- arrays ----
        "length([1,2,3])|3",
        "join([\"a\",\"b\"],\"-\")|\"a-b\"",
        "indexof([1,2,3],2)|1",
        "span([3,7])|4",
        "peek([1,2,3])|3",
        "inrange(5,[0,10])|true",
        // ---- control flow ----
        "if(true,\"a\",\"b\")|\"a\"",
        "if(false,\"a\",\"b\")|\"b\"",
        // ---- ECMA-262 regular expressions ----
        // `split` takes a pattern upstream, and had been stringifying it and splitting on the
        // literal `/\\d+/` — so it returned the whole string, silently. A capture group's text is
        // part of the result, and one that did not participate is a hole rather than an omission.
        "split(\"a1b22c\", regexp(\"\\\\d+\"))|[\"a\",\"b\",\"c\"]",
        "split(\"a1b22c\", regexp(\"(\\\\d)\\\\d*\"))|[\"a\",\"1\",\"b\",\"2\",\"c\"]",
        "split(\"a1b22c\", regexp(\"\\\\d+\"), 2)|[\"a\",\"b\"]",
        "split(\"a1b\", regexp(\"(x)?(\\\\d)\"))|[\"a\",null,\"1\",\"b\"]",
        "split(\"abc\", regexp(\"x\"))|[\"abc\"]",
        // A pattern in a specification is JavaScript's, and Kotlin's `Regex` is the platform's.
        // Each
        // of the first four was measured wrong against upstream before `VegaValue.Pattern` moved to
        // an ECMA-262 engine: Java's `$` matches before a final newline, `\\a` is an identity
        // escape
        // in Annex B and an error in Java, and `x{` and `[]` — ordinary patterns in a browser —
        // *threw*, which is a chart taken down by a pasted string rather than a wrong answer.
        "test(regexp(\"a$\"), \"a\\n\")|false",
        "test(regexp(\"x{\"), \"x{\")|true",
        "test(regexp(\"[]\"), \"a\")|false",
        "test(regexp(\"\\\\a\"), \"a\")|true",
        // The flags mean what they mean in a browser, including the two that used to be dropped.
        "test(regexp(\"^b\",\"m\"), \"a\\nb\")|true",
        "test(regexp(\"a.b\",\"s\"), \"a\\nb\")|true",
        // `$`-substitution in a replacement is JavaScript's, not Kotlin's — and `g` alone decides
        // whether the replacement happens once or throughout.
        "replace(\"Ada Lovelace\", regexp(\"(\\\\w+) (\\\\w+)\"), \"$2, $1\")|\"Lovelace, Ada\"",
        "replace(\"price 5\", regexp(\"(\\\\d)\"), \"[$&]\")|\"price [5]\"",
        "replace(\"a-b-c\", regexp(\"-\",\"g\"), \"+\")|\"a+b+c\"",
        "replace(\"a-b-c\", regexp(\"-\"), \"+\")|\"a+b-c\"",
        // ---- formatting ----
        "format(1234.5678,\".2f\")|\"1234.57\"",
        "format(0.1234,\".1%\")|\"12.3%\"",
        "format(1234567,\",d\")|\"1,234,567\"",
        // d3-format signs a formatted magnitude with U+2212 MINUS SIGN, not an ASCII hyphen —
        // every vector below was read out of the pinned d3-format. `toString` and `+` keep the
        // hyphen, because those are JavaScript's own coercion rather than a format string.
        "format(-5,\"\")|\"−5\"",
        "format(-5,\".2f\")|\"−5.00\"",
        "format(-1234.5,\",.2f\")|\"−1,234.50\"",
        "format(-0.5,\".0%\")|\"−50%\"",
        "format(-7,\"d\")|\"−7\"",
        // Only the leading sign: the exponent keeps its own hyphen.
        "format(-0.005,\".2e\")|\"−5.00e-3\"",
        // A **tie**, which is where a formatter is either exact or merely plausible. 2.675 is
        // stored
        // as 2.67499999999999982…, so every one of these rounds *down* — and 8.835, which is stored
        // just above its tie, rounds up. The engine got the `f` cases right and the `e` and `g`
        // cases
        // wrong for as long as it had a formatter, because it reached those two through Java's
        // `String.format("%.Ne")`, which rounds the shortest printable form rather than the exact
        // value and answers 2.68e+0 where JavaScript's `toExponential` answers 2.67e+0. Read out of
        // upstream with `eval-probe.js`, and the reason `Decimals` now expands the double itself.
        "format(2.675,\".2e\")|\"2.67e+0\"",
        "format(2.675,\".3g\")|\"2.67\"",
        "format(1.005,\".2e\")|\"1.00e+0\"",
        "format(9.995,\".2e\")|\"9.99e+0\"",
        "format(8.835,\".2f\")|\"8.84\"",
        "format(1.0000000000000002,\".17e\")|\"1.00000000000000022e+0\"",
        // `g` and `~`, which the specifier grammar did not accept until these vectors said so. An
        // unparsed specifier is not reported — it falls back to plain number text — so `.3g` had
        // been
        // answering `2.675` where upstream answers `2.67`, which is a wrong label that looks like a
        // right one.
        "format(1200,\".3g\")|\"1.20e+3\"",
        "format(0.000012345,\".3g\")|\"0.0000123\"",
        "format(1e21,\".3g\")|\"1.00e+21\"",
        "format(0,\".3g\")|\"0.00\"",
        "format(-2.675,\".3g\")|\"−2.67\"",
        "format(1.5,\".3~g\")|\"1.5\"",
        "format(1.5,\".3~f\")|\"1.5\"",
        "format(1200,\".3~g\")|\"1.2e+3\"",
        "format(1234.5,\",.3~f\")|\"1,234.5\"",
        "format(-0.001,\".2f\")|\"0.00\"",
        "toString(-5)|\"-5\"",
        "\"\" + -5|\"-5\"",
        // A specifier with no type is d3's `.12~g`, not plain fixed formatting: twelve significant
        // digits, trailing zeros trimmed, exponential outside the range that fits.
        "format(5,\"\")|\"5\"",
        "format(0,\"\")|\"0\"",
        "format(1234.5678,\"\")|\"1234.5678\"",
        "format(0.000001234,\"\")|\"0.000001234\"",
        "format(0.0000001,\"\")|\"1e-7\"",
        "format(123456789012345,\"\")|\"1.23456789012e+14\"",
        "format(1234567,\",\")|\"1,234,567\"",
        "format(1234.5678,\",\")|\"1,234.5678\"",
        // ---- format: the currency symbol ----
        // `$` is a slot of its own in d3's grammar, before the zero-pad flag and the grouping
        // comma, and it goes *inside* the sign: a negative price is the minus, then the symbol.
        "format(1.5,'$0.2f')|\"$1.50\"",
        "format(2,'$0.2f')|\"$2.00\"",
        "format(0,'$0.2f')|\"$0.00\"",
        "format(-1.5,'$0.2f')|\"−$1.50\"",
        "format(1234.5,'$,.2f')|\"$1,234.50\"",
        "format(1234.5,'$.2f')|\"$1234.50\"",
        "format(1500000,'$,d')|\"$1,500,000\"",
        // ---- probability distributions ----
        // Every digit from upstream. `quantileNormal` is an approximation of an inverse with no
        // closed form, so the coefficients are transcribed rather than derived and these vectors
        // are what says the transcription is right.
        "quantileNormal(0.25)|-0.6744897501960816",
        "quantileNormal(0.975)|1.959963984540054",
        "quantileNormal(0.5,10,2)|10",
        "quantileUniform(0.3)|0.3",
        "quantileUniform(0.3,10,20)|13",
        "quantileLogNormal(0.5)|1",
        "densityNormal(0)|0.3989422804014327",
        "cumulativeNormal(1.96)|0.9750021048517795",
        "densityUniform(0.5)|1",
        "cumulativeUniform(0.25)|0.25",
        // ---- luminance ----
        // WCAG relative luminance. Every digit here came out of upstream, and several of these
        // separate implementations that all look right:
        "luminance('#000000')|0",
        "luminance('#ffffff')|1",
        "luminance('red')|0.2126",
        "luminance('steelblue')|0.20562642207624857",
        "luminance('#4c78a8')|0.17796594469803553",
        "luminance('#f80')|0.38868318886144393",
        "luminance('rgb(10, 20, 30)')|0.006585790668061925",
        "luminance('rgb(100%, 0%, 0%)')|0.2126",
        // Either side of the knee: channel 10 takes the linear branch and channel 11 the power one.
        "luminance('#0a0a0a')|0.003035269835488375",
        "luminance('#0b0b0b')|0.0033465357638991604",
        // The vector that tells the two knees apart. A lightness of 4% is a channel of exactly
        // 0.04, which is above WCAG's 0.03928 and below sRGB's 0.04045, so the linear branch would
        // give 0.0030959752 here instead — right to five digits and wrong after that.
        //
        // Asserted as a **bracket** rather than as the value, and this is the one vector here that
        // is: 4% lightness is a fractional channel of 10.2, and the `pow` that follows is allowed a
        // one-ulp latitude that no platform guarantees. For this input that latitude lands on a
        // rounding boundary, so the digits printed on Linux and on macOS differ — `#0a0a0a` beside
        // it, whose channels are whole numbers, agrees everywhere. The bracket keeps what the
        // vector
        // is for, with four significant digits between the two knees and the wobble far inside it.
        "luminance('hsl(0, 0%, 4%)') > 0.0030954|true",
        "luminance('hsl(0, 0%, 4%)') < 0.0030956|true",
        // Fractional channels, which is what an hsl colour has. Rounding them to bytes first gives
        // 0.12512359 rather than this.
        "luminance('hsl(210, 50%, 40%)')|0.1250645743288924",
        // Opacity is not a channel and does not dim anything.
        "luminance('hsla(120, 60%, 25%, 0.5)')|0.09788192429901331",
        // NaN, serialized by JSON.stringify as null: d3 blanks the channels of a colour it cannot
        // read *and* of one whose opacity is zero, so a transparent colour is not black.
        "luminance('nonsense')|null",
        "luminance('transparent')|null",
        "luminance('none')|null",
        "luminance('rgba(255, 0, 0, 0)')|null",
        // ---- grouping, over the leading digits only ----
        //
        // d3 splits a formatted value at the first character that is not a digit and groups what is
        // before it. Splitting on the decimal point alone grouped an *exponent* into the number:
        // `,.1` of 200,000 came out `2,e+5`, which is what an axis over a million actually asks
        // for.
        "format(200000, ',')|\"200,000\"",
        "format(200000, ',.1')|\"2e+5\"",
        "format(1234567, ',.3')|\"1.23e+6\"",
        "format(1234.5678, ',')|\"1,234.5678\"",
        "format(123456, ',.2e')|\"1.23e+5\"",
        "format(12.345, ',.1%')|\"1,234.5%\"",
        // ---- the nine that had no vector at all ----
        //
        // Found by subtracting the names any expression test calls from the names `Functions.kt`
        // registers. Worth doing after `hsl(h, s, l)` turned out to have been returning null: a
        // function nothing calls is a function nothing checks, and the diff takes a second.
        "atan2(1, 2)|0.4636476090008061",
        "atan2(-3, -4)|-2.498091544796509",
        // `bandspace` counts *steps*, not bands, so five bands at 0.1 inner padding come to 5.3 —
        // and the padding is allowed to eat the whole band without the answer going negative, which
        // would invert the scale.
        "bandspace(5, 0.1, 0.2)|5.300000000000001",
        "bandspace(0, 0.1, 0.2)|0",
        "bandspace(3, 0.9, 0)|2.1",
        // `lerp` short-circuits at 0 and 1 rather than computing `lo + f*(hi-lo)`, so the ends are
        // exact rather than within a rounding.
        "lerp([10, 20], 0.25)|12.5",
        "lerp([10, 20], 0)|10",
        "lerp([10, 20], 1)|20",
        "lerp([7], 0.5)|7",
        "join(pluck([{a:1},{a:2},{a:3}], 'a'), ',')|\"1,2,3\"",
        // `stop` is exclusive, and the values are multiplied out from the start rather than
        // accumulated, so a fractional step does not drift.
        "join(sequence(5), ',')|\"0,1,2,3,4\"",
        "join(sequence(2, 8, 2), ',')|\"2,4,6\"",
        "join(sequence(0, 1, 0.25), ',')|\"0,0.25,0.5,0.75\"",
        "join(sort([3, 1, 2]), ',')|\"1,2,3\"",
        "join(sort(['b','a','c']), ',')|\"a,b,c\"",
        "trim('  padded  ')|\"padded\"",
        "trim('')|\"\"",
        // Local time, and the suite pins the zone: mid-January in Amsterdam is UTC+1, which
        // JavaScript reports as a *negative* offset in minutes.
        "timezoneoffset(datetime(2024, 0, 15))|-60",
        // `timeSequence` steps in **local** time even when the result is read as UTC, which is why
        // the first entry reads as the last day of the previous year.
        "length(timeSequence('month', datetime(2024,0,1), datetime(2024,4,1)))|4",
        "utcFormat(timeSequence('month', datetime(2024,0,1), datetime(2024,4,1))[0], " +
          "'%Y-%m-%d')|\"2023-12-31\"",
        "utcFormat(timeSequence('month', datetime(2024,0,1), datetime(2024,4,1))[3], " +
          "'%Y-%m-%d')|\"2024-03-31\"",
        // ---- rgb, hsl, lab, hcl: components in, or a colour read apart ----
        //
        // The builders were **returning null**: a Kotlin string template had been escaped into its
        // own literal text, so `hsl(210, 0.6, 0.4)` parsed the string `hsl($h, ${s * 100}%, ...)`
        // and got nothing. Nothing noticed, because every test here read a colour *apart* and none
        // built one. `s` and `l` are fractions, which is d3's convention rather than CSS's.
        "''+hsl(210, 0.6, 0.4)|\"rgb(41, 102, 163)\"",
        "''+rgb(31, 119, 180)|\"rgb(31, 119, 180)\"",
        "''+rgb('steelblue')|\"rgb(70, 130, 180)\"",
        // Reading a colour apart gives the components. Upstream's one object both stringifies as a
        // colour *and* exposes them; a `VegaValue` is one or the other, so the two uses are split
        // by
        // arity — see the note on `hsl` in `Functions.kt`. What a specification does with it is
        // read
        // a channel, shift it and build a new colour, which both halves above support.
        "format(hsl('#4c78a8').h, '.4f')|\"211.3043\"",
        "format(hsl('#4c78a8').s, '.4f')|\"0.3770\"",
        "format(hsl('#4c78a8').l, '.4f')|\"0.4784\"",
        // `lab` and `hcl`, whose components are *not* fractions: a Lab lightness runs 0 to 100 and
        // an
        // HCL chroma is a radius in those units. Reading them the way `hsl` reads its own gives a
        // colour that is nearly black for every input.
        "''+lab(50, 20, -30)|\"rgb(133, 108, 170)\"",
        "''+hcl(120, 40, 60)|\"rgb(125, 154, 81)\"",
        "format(lab('#4c78a8').l, '.4f')|\"48.8173\"",
        // A typographic minus, U+2212, which is what `d3-format` writes and this engine already
        // reproduces everywhere else it formats a negative number.
        "format(lab('#4c78a8').a, '.4f')|\"\u22124.7035\"",
        "format(lab('#4c78a8').b, '.4f')|\"\u221230.8117\"",
        "format(hcl('#4c78a8').h, '.4f')|\"261.3207\"",
        "format(hcl('#4c78a8').c, '.4f')|\"31.1686\"",
        // ---- contrast ----
        // The WCAG ratio, which is symmetric: the brighter colour always goes on top, so writing
        // the pair either way round gives the same answer and it is never below 1.
        "contrast('#000000','#ffffff')|21",
        "contrast('#ffffff','#000000')|21",
        "contrast('steelblue','steelblue')|1",
        // The pair the grouped-bar chart asks about, and why the answer is not obvious: white and
        // black are within 1% of each other against Vega's default blue, so an approximation that
        // is right to two digits still picks the wrong label colour.
        "contrast('white','#4c78a8')|4.6059511274406955",
        "contrast('black','#4c78a8')|4.559318893960711",
        "contrast('white','#f58518')|2.5452396422570263",
        "contrast('black','#f58518')|8.250696575422642",
        "contrast('hsl(210, 50%, 40%)','#0a0a0a')|3.3009085250613452",
        // A luminance of NaN carries through both the max and the min, so the ratio is NaN and
        // every comparison against it is false — which is how an unreadable colour behaves.
        "contrast('nonsense','white')|null",
        "contrast('transparent','white')|null",
        // ---- containerSize ----
        // No DOM, so this is upstream's own headless answer: two absent values, not [0, 0].
        "containerSize()|[null,null]",
        "length(containerSize())|2",
        "isValid(containerSize()[0])|false",
        "containerSize()[0] == null|true",
      ],
  )
  fun `functions match upstream Vega`(source: String, expected: String) {
    assertEquals(expected, evaluate(source), "expression: $source")
  }

  @Test
  fun `array and object results match upstream`() {
    assertEquals("[\"a\",\"b\",\"c\"]", evaluate("split(\"a,b,c\",\",\")"))
    assertEquals("[3,2,1]", evaluate("reverse([1,2,3])"))
    assertEquals("[2,3]", evaluate("slice([1,2,3,4],1,3)"))
    assertEquals("[3,4]", evaluate("slice([1,2,3,4],-2)"))
    assertEquals("[1,5]", evaluate("clampRange([1,5],0,10)"))
    assertEquals("[0,10]", evaluate("clampRange([-5,5],0,10)"))
    assertEquals("[0,10]", evaluate("clampRange([0,20],0,10)"))
    assertEquals("\"abcd…\"", evaluate("truncate(\"abcdefgh\",5)"))
  }

  @Test
  fun `operators containing the csv delimiter match upstream`() {
    // These cannot live in the CSV table: `|` and `||` are the table's own delimiter, and an empty
    // string literal does not survive CSV quoting.
    assertEquals("3", evaluate("1 | 2 ^ 3 & 4"))
    // `||` reads as two delimiters in the CSV table, so it lives here too.
    assertEquals("\"fallback\"", evaluate("\"\" || \"fallback\""))
    assertEquals("\"x\"", evaluate("\"x\" || \"y\""))
    assertEquals("0", evaluate("+\"\""))
    assertEquals("0", evaluate("toNumber(\"\")"))
  }

  @Test
  fun `object literals support both quoted and bare keys`() {
    assertEquals("1", evaluate("{\"a\": 1}.a"))
    assertEquals("1", evaluate("{a: 1}[\"a\"]"))
  }

  /**
   * Date functions, pinned against upstream.
   *
   * Only the `utc` half is checked here, deliberately: the local-time half reads whatever zone the
   * machine is in, so a reference vector for it would pass in one place and fail in another. The
   * two share every line of implementation past the zone they are handed, and `TimeScaleTest`
   * covers the zone-dependent behaviour with zones it names explicitly.
   */
  @ParameterizedTest(name = "{0}")
  @CsvSource(
    delimiter = '|',
    value =
      [
        // ---- accessors: month and day-of-week are zero-based, quarter and day-of-year are not
        // ----
        "utcyear(utc(2026, 2, 14))|2026",
        "utcquarter(utc(2026, 2, 14))|1",
        "utcmonth(utc(2026, 2, 14))|2",
        "utcdate(utc(2026, 2, 14))|14",
        "utcday(utc(2026, 2, 14))|6",
        "utcdayofyear(utc(2026, 2, 14))|73",
        "utchours(utc(2026, 2, 14, 9, 5, 3, 250))|9",
        "utcminutes(utc(2026, 2, 14, 9, 5, 3, 250))|5",
        "utcseconds(utc(2026, 2, 14, 9, 5, 3, 250))|3",
        "utcmilliseconds(utc(2026, 2, 14, 9, 5, 3, 250))|250",
        // ---- construction rolls over, as JavaScript's Date does ----
        "utc(2026, 12, 1)|1798761600000",
        "utc(2026, 0, 32)|1769904000000",
        "utc(2026, 0, 1) - utc(2025, 11, 31)|86400000",
        "time(utc(2026, 0, 1))|1767225600000",
        // ---- formatting ----
        "utcFormat(utc(2026, 2, 14, 9, 5), '%Y-%m-%d %H:%M')|\"2026-03-14 09:05\"",
        "utcFormat(utc(2026, 0, 5), '%B %d, %Y')|\"January 05, 2026\"",
        "utcFormat(utc(2026, 0, 5), '%a %b %e')|\"Mon Jan  5\"",
        "utcFormat(utc(2026, 0, 5), '%j')|\"005\"",
        "utcFormat(utc(2026, 6, 4, 13, 7), '%I:%M %p')|\"01:07 PM\"",
        "utcFormat(utc(2026, 6, 4), '%y')|\"26\"",
        // `%q` is Vega's own directive and `%U` counts Sunday boundaries from the year's start, so
        // a year opening on a Sunday has no week 0 and one opening on a Tuesday does.
        "utcFormat(utc(2012, 4, 15), 'Q%q W%U')|\"Q2 W20\"",
        "utcFormat(utc(2012, 0, 1), 'W%U')|\"W01\"",
        "utcFormat(utc(2013, 0, 1), 'W%U')|\"W00\"",
        "utcFormat(utc(2013, 0, 5), 'W%U')|\"W00\"",
        "utcFormat(utc(2013, 0, 6), 'W%U')|\"W01\"",
        "utcFormat(utc(2026, 11, 31), 'Q%q W%U')|\"Q4 W52\"",
        // ---- the format a set of time units is labelled with ----
        // The longest recognised *run* wins, which is what collapses three units into one field,
        // and the units are put in calendar order before the runs are matched.
        "timeUnitSpecifier(['day'], {hours:'%H'})|\"%a\"",
        "timeUnitSpecifier(['year','month'])|\"%Y-%m\"",
        "timeUnitSpecifier(['date','year','month'])|\"%Y-%m-%d\"",
        "timeUnitSpecifier(['quarter'])|\"Q%q\"",
        "timeUnitSpecifier(['week'])|\"W%U\"",
        "timeUnitSpecifier(['hours','minutes'])|\"%H:%M\"",
        "timeUnitSpecifier(['date','hours'])|\"%d %H:00\"",
        "timeUnitSpecifier(['seconds'])|\":%S\"",
        "timeUnitSpecifier('month')|\"%b\"",
        // ---- moving a date by whole units ----
        // The step defaults to one and is *floored*; an absent argument is not `Number()`-coerced
        // to zero, which would hand the date straight back. Both forms below are the ones a
        // specification writes, and the two-argument one is the common one.
        // ---- month and weekday names ----
        // Upstream produces these by formatting a date it builds for the purpose, so both
        // indices wrap: month 12 is January again and day -1 is Saturday. A non-integer gives
        // the empty string rather than a name for a day that does not exist.
        "monthFormat(0)|\"January\"",
        "monthFormat(11)|\"December\"",
        "monthFormat(12)|\"January\"",
        "monthFormat(-1)|\"December\"",
        "monthAbbrevFormat(2)|\"Mar\"",
        "monthFormat(1.5)|\"\"",
        "dayFormat(0)|\"Sunday\"",
        "dayFormat(6)|\"Saturday\"",
        "dayFormat(7)|\"Sunday\"",
        "dayFormat(-1)|\"Saturday\"",
        "dayAbbrevFormat(3)|\"Wed\"",
        // ---- week numbers ----
        // Sundays since the start of the year, not ISO weeks: the days before the first
        // Sunday are week 0, and a year beginning on a Sunday has its first day in week 1.
        "week(datetime(2020, 0, 5))|1",
        "week(datetime(2021, 0, 1))|0",
        "week(datetime(2017, 0, 1))|1",
        "week(datetime(2020, 11, 31))|52",
        "utcweek(datetime(2020, 0, 5))|0",
        // ---- the UTC twins of timeOffset and timeSequence ----
        // A local midnight in Amsterdam is 23:00 the day before in UTC, which is the whole
        // reason both exist: "one day later" is 24 hours in UTC and 23 or 25 across a clock
        // change locally.
        "utcFormat(utcOffset('day', datetime(2020,0,1), 3), '%Y-%m-%d %H:%M')|\"2020-01-03 23:00\"",
        "utcFormat(utcOffset('month', datetime(2020,0,31), 1), '%Y-%m-%d %H:%M')|\"2020-03-01 23:00\"",
        "length(utcSequence('day', datetime(2020,0,1), datetime(2020,0,4)))|3",
        "utcFormat(utcSequence('day', datetime(2020,0,1), datetime(2020,0,4))[0], " +
          "'%Y-%m-%d %H:%M')|\"2020-01-01 00:00\"",
        "utcFormat(utcSequence('month', datetime(2020,0,1), datetime(2020,6,1), 2)[1], " +
          "'%Y-%m-%d %H:%M')|\"2020-03-01 00:00\"",
        // A sequence yields the unit **boundaries**, so a start at noon is ceiled to the next
        // midnight rather than stepped from. This pair contradicted the implementation, which
        // walked from the start itself and carried a comment claiming that was upstream's rule.
        "length(timeSequence('day', datetime(2020,0,1,12), datetime(2020,0,4)))|2",
        "timeFormat(timeSequence('day', datetime(2020,0,1,12), datetime(2020,0,4))[0], " +
          "'%m-%d %H:%M')|\"01-02 00:00\"",
        // ---- pan and zoom ----
        // What an interactive chart's `domainRaw` is written with. Each pair lifts the
        // interval into the space its gesture is linear in, moves it there and puts it back.
        "panLinear([0, 10], 0.5)|[-5,5]",
        "panLinear([0, 10], -0.25)|[2.5,12.5]",
        "panLog([1, 100], 0.5)|[0.09999999999999998,10.000000000000002]",
        "panPow([1, 10], 0.5, 2)|[-6.96419413859206,7.106335201775948]",
        "panSymlog([-10, 10], 0.5, 1)|[-120.00000000000003,0]",
        "zoomLinear([0, 10], 5, 2)|[-5,15]",
        // A null anchor is the interval's own midpoint, which is what makes a zoom with no
        // pointer position behave like one centred on the plot.
        "zoomLinear([0, 10], null, 2)|[-5,15]",
        "zoomLog([1, 100], 10, 2)|[0.09999999999999998,1000.0000000000007]",
        "zoomPow([1, 10], 5, 2, 2)|[-4.795831523312719,13.228756555322953]",
        "zoomSymlog([-10, 10], 0, 2, 1)|[-120.00000000000003,120.00000000000003]",
        // ---- merge and flush ----
        // `merge` is `extend({}, ...)`: shallow, later arguments winning, and a key keeps the
        // position of its *first* appearance while taking its value from the last.
        "merge({a: 1}, {b: 2}, {a: 3})|{\"a\":3,\"b\":2}",
        "merge()|{}",
        // `flush`, the rule the axis builder already uses for `labelFlush`: the ends are
        // sorted before the comparison, so a descending range still answers for its low end.
        "flush([0, 100], 3, 5, 'L', 'R', 'C')|\"L\"",
        "flush([0, 100], 97, 5, 'L', 'R', 'C')|\"R\"",
        "flush([0, 100], 50, 5, 'L', 'R', 'C')|\"C\"",
        "flush([100, 0], 2, 5, 'L', 'R', 'C')|\"L\"",
        // ---- lasso and pinch geometry ----
        // `lassoAppend` adds the point only if it is **strictly** further than `minDist` from the
        // last, which defaults to 5 — so a drag that has not moved six units returns the same
        // array.
        "lassoAppend([], 10, 20)|[[10,20]]",
        "lassoAppend([[0,0]], 3, 4)|[[0,0]]",
        "lassoAppend([[0,0]], 30, 40)|[[0,0],[30,40]]",
        "lassoAppend([[0,0]], 3, 4, 1)|[[0,0],[3,4]]",
        // `lassoPath` is transcribed spacing and all: the **last** point becomes " Z" and is never
        // written, which is why a three-point lasso has two spaces before the Z, and a one-point
        // one
        // takes the first branch rather than the last.
        "lassoPath([[0,0],[10,0],[10,10]])|\"M 0,0 L 10,0  Z\"",
        "lassoPath([])|\"\"",
        "lassoPath([[1,2]])|\"M 1,2 \"",
        // The pinch pair is arithmetic over two touches and nothing else about a browser.
        "pinchDistance({touches: [{clientX: 0, clientY: 0}, {clientX: 3, clientY: 4}]})|5",
        "pinchAngle({touches: [{clientX: 0, clientY: 0}, {clientX: 3, clientY: 4}]})|-2.214297435588181",
        // ---- messages a specification sends itself ----
        // Each returns its **last** argument, which is what lets one wrap a value without changing
        // what the expression computes. The message goes to the diagnostics.
        "warn('hi', 42)|42",
        "info(1, 2)|2",
        "debug('x')|\"x\"",
        // ---- the headless answers ----
        // Upstream in a `renderer: 'none'` view, which is what the oracle renders every fixture in:
        // no window means an empty object and a pair of absent numbers, not zeroes and not the
        // view's own size.
        // ---- reading a date back out of a string ----
        // `timeParse` reads in local time and `utcParse` in UTC, which is the whole difference
        // between the first two. What is not written defaults to **1900-01-01**, not to today, so a
        // specifier of `%I:%M %p` puts its time on the first of January 1900.
        "utcFormat(timeParse('2020-03-15', '%Y-%m-%d'), '%Y-%m-%dT%H:%M')|\"2020-03-14T23:00\"",
        "utcFormat(utcParse('2020-03-15', '%Y-%m-%d'), '%Y-%m-%dT%H:%M')|\"2020-03-15T00:00\"",
        "utcFormat(timeParse('15/03/2020 14:30', '%d/%m/%Y %H:%M'), " +
          "'%Y-%m-%dT%H:%M')|\"2020-03-15T13:30\"",
        "utcFormat(timeParse('March 15 2020', '%B %d %Y'), '%Y-%m-%dT%H:%M')|\"2020-03-14T23:00\"",
        "utcFormat(timeParse('Mar 15 20', '%b %d %y'), '%Y-%m-%dT%H:%M')|\"2020-03-14T23:00\"",
        "utcFormat(utcParse('2020-03-15 02:03:04.567', '%Y-%m-%d %H:%M:%S.%L'), " +
          "'%H:%M:%S.%L')|\"02:03:04.567\"",
        "utcFormat(utcParse('2020-075', '%Y-%j'), '%Y-%m-%d')|\"2020-03-15\"",
        "utcFormat(utcParse('11:30 PM', '%I:%M %p'), '%Y-%m-%dT%H:%M')|\"1900-01-01T23:30\"",
        "utcFormat(utcParse('12:30 AM', '%I:%M %p'), '%Y-%m-%dT%H:%M')|\"1900-01-01T00:30\"",
        "utcFormat(utcParse('2020', '%Y'), '%Y-%m-%dT%H:%M')|\"2020-01-01T00:00\"",
        "utcFormat(utcParse('2020-03-15T10:00:00Z', '%Y-%m-%dT%H:%M:%S%Z'), " +
          "'%Y-%m-%dT%H:%M')|\"2020-03-15T10:00\"",
        "utcFormat(utcParse('2020-03-15T10:00:00+0200', '%Y-%m-%dT%H:%M:%S%Z'), " +
          "'%Y-%m-%dT%H:%M')|\"2020-03-15T08:00\"",
        "utcFormat(utcParse('2020-03-15T10:00:00+02:00', '%Y-%m-%dT%H:%M:%S%Z'), " +
          "'%Y-%m-%dT%H:%M')|\"2020-03-15T08:00\"",
        "utcFormat(utcParse(' 5 Jan 2020', '%d %b %Y'), '%Y-%m-%d')|\"2020-01-05\"",
        "utcFormat(utcParse('Sunday', '%A'), '%Y-%m-%d')|\"1900-01-01\"",
        "utcFormat(utcParse('50%', '%d%%'), '%Y-%m-%d')|\"1900-02-19\"",
        // The string and the specifier must match **exactly**: trailing input is a failure, not
        // a date, and neither is a string the specifier cannot walk.
        "timeParse('nonsense', '%Y-%m-%d')|null",
        "timeParse('2020-03-15 extra', '%Y-%m-%d')|null",
        // Overflow normalises as `new Date` normalises it: day 50 of January is the 19th of
        // February, which is also what makes `%j` able to name the last day of a leap year.
        // ---- what a date is ----
        // `typeof new Date()` is `"object"`, so a date is **not a number** on either side even
        // though it adds and compares like one. `datetime` builds a Date and `utc` builds
        // milliseconds, which is why the two answer differently; `now()` is milliseconds too.
        "isDate(datetime(2020,0,1))|true",
        "isNumber(datetime(2020,0,1))|false",
        "isObject(datetime(2020,0,1))|true",
        "isValid(datetime(2020,0,1))|true",
        "isDate(utc(2020,0,1))|false",
        "isNumber(utc(2020,0,1))|true",
        "isDate(now())|false",
        "isNumber(now())|true",
        "isDate(5)|false",
        "isDate('x')|false",
        "isDate(timeParse('2020','%Y'))|true",
        "isDate(timeOffset('day', datetime(2020,0,1)))|true",
        // Arithmetic and comparison are unaffected, which is the point of keeping it a number
        // underneath.
        "datetime(2020,0,1) < datetime(2020,0,2)|true",
        "datetime(2020,0,2) - datetime(2020,0,1)|86400000",
        // ---- what the view-bound functions answer with no view ----
        // Each of these is upstream's answer in the same position, not a placeholder. A signal is
        // resolved before the scenegraph exists, so `intersect` over a chart full of marks answers
        // `[]` there too; `inScope` is false wherever there is no enclosing group; `copy` returns a
        // scale function that `isValid` rejects, which null also is; and `encode` hands back its
        // third argument.
        "intersect([[0,0],[10,10]])|[]",
        "inScope(null)|false",
        "isValid(copy('x'))|false",
        "encode(null, 'update', 7)|7",
        "isRegExp(1)|false",
        "isRegExp('x')|false",
        "screen()|{}",
        "windowSize()|[null,null]",
        "timeFormat(timeOffset('day', datetime(2019,2,31)), '%Y-%m-%d %H:%M')|\"2019-04-01 00:00\"",
        "timeFormat(timeOffset('day', datetime(2019,2,31), 2), '%Y-%m-%d %H:%M')|\"2019-04-02 00:00\"",
        "timeFormat(timeOffset('day', datetime(2019,2,31), 0), '%Y-%m-%d %H:%M')|\"2019-03-31 00:00\"",
        "timeFormat(timeOffset('day', datetime(2019,2,31), null), '%Y-%m-%d %H:%M')|\"2019-04-01 00:00\"",
        "timeFormat(timeOffset('day', datetime(2019,2,31), 1.7), '%Y-%m-%d %H:%M')|\"2019-04-01 00:00\"",
        // A month or year step **overflows** rather than clamping, because that is what
        // `Date.setMonth` does: 31 January plus a month asks for "31 February", which normalises to
        // 2 March in a leap year and 3 March otherwise. Clamping to the 29th put every date past
        // the
        // 28th one to three days early, and the tick generator never noticed because it only ever
        // offsets from the first of a month.
        "timeFormat(timeOffset('month', datetime(2020,0,31), 1), '%Y-%m-%d')|\"2020-03-02\"",
        "timeFormat(timeOffset('month', datetime(2020,4,31), 1), '%Y-%m-%d')|\"2020-07-01\"",
        "timeFormat(timeOffset('month', datetime(2021,0,31), -1), '%Y-%m-%d')|\"2020-12-31\"",
        "timeFormat(timeOffset('year', datetime(2020,1,29), 1), '%Y-%m-%d')|\"2021-03-01\"",
        "timeFormat(timeOffset('day', datetime(2019,2,31), -1), '%Y-%m-%d %H:%M')|\"2019-03-30 00:00\"",
        // ---- reading ----
        "toDate('2026-01-05T00:00:00Z')|1767571200000",
        "utcyear(toDate('2026-01-05T00:00:00Z'))|2026",
        "utcyear(1767225600000)|2026",
      ],
  )
  fun `date functions match upstream`(expression: String, expected: String) {
    assertEquals(expected, evaluate(expression), expression)
  }

  /**
   * `indata` against a dataset holding one of every value kind, pinned against upstream.
   *
   * The point of the table is the coercion. Upstream indexes a dataset by the field value coerced
   * to a string and looks the argument up the same way, so `indata('t', 'k', 1)` finds the row
   * whose `k` is the *string* `"1"`, and the boolean `true` finds the string `"true"`. An
   * implementation that compares with `===` — which is what the documented "matches value" suggests
   * — returns nothing for four of these rows and looks perfectly reasonable while doing it.
   *
   * The result is a **count**, not a boolean: `'a'` appears twice and upstream answers 2.
   */
  @ParameterizedTest(name = "{0}")
  @CsvSource(
    delimiter = '|',
    value =
      [
        "indata('t', 'k', 'a')|2",
        "indata('t', 'k', 'b')|1",
        // Upstream answers **undefined** for a value no row carries, not null. Probed.
        "indata('t', 'k', 'zzz')|undefined",
        // The row whose k is the string "1", found by the number 1.
        "indata('t', 'k', 1)|1",
        // The row whose k is the number 5, found by either spelling.
        "indata('t', 'k', 5)|1",
        "indata('t', 'k', '5')|1",
        "indata('t', 'k', null)|1",
        "indata('t', 'k', true)|1",
        "indata('t', 'k', 'true')|1",
        "indata('t', 'n', 3)|1",
        "indata('t', 'n', '3')|1",
        // A field no row has: upstream groups them all under one absent key, which nothing matches.
        "indata('t', 'nosuchfield', 'a')|undefined",
        "if(indata('t', 'k', 'a'), 'yes', 'no')|\"yes\"",
        "if(indata('t', 'k', 'zzz'), 'yes', 'no')|\"no\"",
      ],
  )
  fun `indata matches upstream`(expression: String, expected: String) {
    val result = compiler.compile(expression)
    assertTrue(result is ExpressionResult.Compiled, "failed to parse '$expression': $result")
    assertEquals(
      expected,
      asJson((result as ExpressionResult.Compiled).expression.evaluate(IndataScope)),
      expression,
    )
  }

  /** The dataset the `indata` table is read against, matching the one the oracle was run on. */
  private object IndataScope : ExpressionScope {
    override val datum: VegaValue = VegaValue.EmptyObject

    override fun signal(name: String): VegaValue = VegaValue.Null

    private fun row(k: VegaValue, n: Double): VegaValue =
      VegaValue.Obj(linkedMapOf("k" to k, "n" to VegaValue.Num(n)))

    private val rows =
      listOf(
        row(VegaValue.Str("a"), 1.0),
        row(VegaValue.Str("a"), 2.0),
        row(VegaValue.Str("b"), 3.0),
        row(VegaValue.Str("1"), 4.0),
        row(VegaValue.Num(5.0), 5.0),
        row(VegaValue.Null, 6.0),
        row(VegaValue.Bool(true), 7.0),
      )

    override fun dataset(name: String): List<VegaValue> = if (name == "t") rows else emptyList()
  }
}
