package dev.aster.vega.expression

import dev.aster.vega.model.VegaValue
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.CsvSource

/**
 * Reference vectors for the expression engine, every one generated by evaluating the expression
 * with upstream Vega (`oracle-js/src/eval-probe.js`).
 *
 * The expected column is what Vega actually returns, serialized as JSON — so `NaN` and `Infinity`
 * appear as `null`, exactly as they do coming out of the oracle. These are not restatements of the
 * implementation: several of them contradicted a first, reasonable-looking implementation and were
 * the reason it changed.
 */
class ExpressionReferenceTest {

  private val compiler = VegaExpressionCompiler()

  /**
   * Evaluates and renders the result the way `JSON.stringify` would, for comparison with the
   * oracle.
   */
  private fun evaluate(source: String): String {
    val result = compiler.compile(source)
    assertTrue(result is ExpressionResult.Compiled, "failed to parse '$source': $result")
    val expression = (result as ExpressionResult.Compiled).expression
    return asJson(expression.evaluate(EmptyScope))
  }

  private fun asJson(value: VegaValue): String =
    when (value) {
      is VegaValue.Null -> "null"
      is VegaValue.Bool -> value.value.toString()
      // JSON has no NaN or Infinity, so JSON.stringify emits null; match that.
      is VegaValue.Num ->
        if (!value.value.isFinite()) "null" else JsSemantics.numberToString(value.value)
      is VegaValue.Timestamp -> JsSemantics.numberToString(value.epochMillis)
      is VegaValue.Str -> "\"${value.value}\""
      is VegaValue.Arr -> value.values.joinToString(",", "[", "]") { asJson(it) }
      is VegaValue.Obj ->
        value.fields.entries.joinToString(",", "{", "}") { "\"${it.key}\":${asJson(it.value)}" }
    }

  private object EmptyScope : ExpressionScope {
    override val datum: VegaValue = VegaValue.EmptyObject

    override fun signal(name: String): VegaValue = VegaValue.Null

    override fun dataset(name: String): List<VegaValue> = emptyList()
  }

  @ParameterizedTest(name = "{0} => {1}")
  @CsvSource(
    delimiter = '|',
    value =
      [
        // ---- arithmetic and precedence ----
        "1 + 2|3",
        "2 + 3 * 4|14",
        "(2 + 3) * 4|20",
        "2 - 3 - 4|-5",
        "2 * 3 % 4|2",
        "7 / 2|3.5",
        "7 % 3|1",
        "-7 % 3|-1",
        "1 / 0|null",
        "0 / 0|null",
        "true + true|2",
        // ---- string concatenation, the surprising operator ----
        "1 + \"2\"|\"12\"",
        "\"a\" + \"b\"|\"ab\"",
        "\"a\" + 1 + 2|\"a12\"",
        "1 + 2 + \"a\"|\"3a\"",
        "null + 1|1",
        "null + \"a\"|\"nulla\"",
        // An array primitivizes to a string for `+`, so this concatenates rather than adds.
        "[1] + 1|\"11\"",
        "[1,2] + \"\"|\"1,2\"",
        // ---- equality ----
        "1 == \"1\"|true",
        "1 === \"1\"|false",
        "\"\" == 0|true",
        "1 + 2 == 3|true",
        "1 < 2 == true|true",
        "!true == false|true",
        // ---- relational ----
        "1 < 2|true",
        "10 < 9|false",
        "\"a\" < \"b\"|true",
        // Both operands are strings, so this is lexicographic, not numeric.
        "\"10\" < \"9\"|true",
        // ---- logical, unary, bitwise ----
        "!0|true",
        "!\"\"|true",
        "!\"a\"|false",
        "-\"3\"|-3",
        "+\"3\"|3",
        "~5|-6",
        // Unary minus binds tighter than `^`, and `^` is XOR, not exponentiation.
        "-2 ^ 2|-4",
        "1 << 2 + 1|8",
        "8 >> 1 >> 1|2",
        "-1 >>> 28|15",
        "\"x\" && \"y\"|\"y\"",
        // ---- conditional ----
        "1 ? \"y\" : \"n\"|\"y\"",
        "0 ? \"y\" : \"n\"|\"n\"",
        "true ? 1 : 2 ? 3 : 4|1",
        "0 ? 1 : 0 ? 3 : 4|4",
        // ---- numeric coercion of strings ----
        "+\" 12 \"|12",
        "+\"1e3\"|1000",
        "+\"0x10\"|16",
        "+\"abc\"|null",
        // ---- members, literals, constants ----
        "[1,2,3][1]|2",
        "[1,2,3].length|3",
        "\"abc\".length|3",
        "\"abc\"[1]|\"b\"",
        "PI > 3|true",
        "E > 2|true",
        "sqrt(2) == SQRT2|true",
      ],
  )
  fun `matches upstream Vega`(source: String, expected: String) {
    assertEquals(expected, evaluate(source), "expression: $source")
  }

  @ParameterizedTest(name = "{0} => {1}")
  @CsvSource(
    delimiter = '|',
    value =
      [
        // ---- math ----
        "abs(-3)|3",
        // `hypot` is variadic, not the two-argument function its name suggests, and with no
        // arguments it is zero.
        "hypot(3,4)|5",
        "hypot()|0",
        "hypot(1)|1",
        "hypot(1,2,2)|3",
        "isFinite(hypot(-3,-4))|true",
        "floor(2.7)|2",
        "ceil(2.1)|3",
        "sqrt(16)|4",
        "pow(2,10)|1024",
        "min(3,1,2)|1",
        "max(3,1,2)|3",
        "max(1)|1",
        // Vega's min/max are Math.min/Math.max: variadic, so an array argument is NaN, not a
        // reduction.
        "min([5,2,9])|null",
        "clamp(5,0,3)|3",
        // JavaScript rounds halves toward positive infinity.
        "round(0.5)|1",
        "round(-0.5)|0",
        "round(1.5)|2",
        "round(2.5)|3",
        "round(-2.5)|-2",
        // ---- predicates ----
        "isNumber(1)|true",
        "isString(\"a\")|true",
        "isArray([])|true",
        "isBoolean(true)|true",
        "isValid(null)|false",
        "isValid(1)|true",
        "isValid(0)|true",
        "isValid(\"\")|true",
        "isValid(NaN)|false",
        // ---- coercion ----
        "toNumber(\"42\")|42",
        "toString(42)|\"42\"",
        // Upstream returns null, not false, for the empty string.
        "toBoolean(\"\")|null",
        "toBoolean(0)|false",
        "toBoolean(\"x\")|true",
        "parseInt(\"42px\")|42",
        "parseFloat(\"3.5rem\")|3.5",
        "parseInt(\"ff\",16)|255",
        // ---- strings ----
        "upper(\"ab\")|\"AB\"",
        "lower(\"AB\")|\"ab\"",
        "substring(\"hello\",1,3)|\"el\"",
        "indexof(\"hello\",\"l\")|2",
        "lastindexof(\"abcabc\",\"b\")|4",
        "replace(\"a-b\",\"-\",\"+\")|\"a+b\"",
        "pad(\"5\",3,\"0\",\"left\")|\"005\"",
        "lower(\"ABC\") + upper(\"de\")|\"abcDE\"",
        // ---- arrays ----
        "length([1,2,3])|3",
        "join([\"a\",\"b\"],\"-\")|\"a-b\"",
        "indexof([1,2,3],2)|1",
        "span([3,7])|4",
        "peek([1,2,3])|3",
        "inrange(5,[0,10])|true",
        // ---- control flow ----
        "if(true,\"a\",\"b\")|\"a\"",
        "if(false,\"a\",\"b\")|\"b\"",
        // ---- formatting ----
        "format(1234.5678,\".2f\")|\"1234.57\"",
        "format(0.1234,\".1%\")|\"12.3%\"",
        "format(1234567,\",d\")|\"1,234,567\"",
        // d3-format signs a formatted magnitude with U+2212 MINUS SIGN, not an ASCII hyphen —
        // every vector below was read out of the pinned d3-format. `toString` and `+` keep the
        // hyphen, because those are JavaScript's own coercion rather than a format string.
        "format(-5,\"\")|\"−5\"",
        "format(-5,\".2f\")|\"−5.00\"",
        "format(-1234.5,\",.2f\")|\"−1,234.50\"",
        "format(-0.5,\".0%\")|\"−50%\"",
        "format(-7,\"d\")|\"−7\"",
        // Only the leading sign: the exponent keeps its own hyphen.
        "format(-0.005,\".2e\")|\"−5.00e-3\"",
        "format(-0.001,\".2f\")|\"0.00\"",
        "toString(-5)|\"-5\"",
        "\"\" + -5|\"-5\"",
        // A specifier with no type is d3's `.12~g`, not plain fixed formatting: twelve significant
        // digits, trailing zeros trimmed, exponential outside the range that fits.
        "format(5,\"\")|\"5\"",
        "format(0,\"\")|\"0\"",
        "format(1234.5678,\"\")|\"1234.5678\"",
        "format(0.000001234,\"\")|\"0.000001234\"",
        "format(0.0000001,\"\")|\"1e-7\"",
        "format(123456789012345,\"\")|\"1.23456789012e+14\"",
        "format(1234567,\",\")|\"1,234,567\"",
        "format(1234.5678,\",\")|\"1,234.5678\"",
        // ---- format: the currency symbol ----
        // `$` is a slot of its own in d3's grammar, before the zero-pad flag and the grouping
        // comma, and it goes *inside* the sign: a negative price is the minus, then the symbol.
        "format(1.5,'$0.2f')|\"$1.50\"",
        "format(2,'$0.2f')|\"$2.00\"",
        "format(0,'$0.2f')|\"$0.00\"",
        "format(-1.5,'$0.2f')|\"−$1.50\"",
        "format(1234.5,'$,.2f')|\"$1,234.50\"",
        "format(1234.5,'$.2f')|\"$1234.50\"",
        "format(1500000,'$,d')|\"$1,500,000\"",
        // ---- probability distributions ----
        // Every digit from upstream. `quantileNormal` is an approximation of an inverse with no
        // closed form, so the coefficients are transcribed rather than derived and these vectors
        // are what says the transcription is right.
        "quantileNormal(0.25)|-0.6744897501960816",
        "quantileNormal(0.975)|1.959963984540054",
        "quantileNormal(0.5,10,2)|10",
        "quantileUniform(0.3)|0.3",
        "quantileUniform(0.3,10,20)|13",
        "quantileLogNormal(0.5)|1",
        "densityNormal(0)|0.3989422804014327",
        "cumulativeNormal(1.96)|0.9750021048517795",
        "densityUniform(0.5)|1",
        "cumulativeUniform(0.25)|0.25",
        // ---- luminance ----
        // WCAG relative luminance. Every digit here came out of upstream, and several of these
        // separate implementations that all look right:
        "luminance('#000000')|0",
        "luminance('#ffffff')|1",
        "luminance('red')|0.2126",
        "luminance('steelblue')|0.20562642207624857",
        "luminance('#4c78a8')|0.17796594469803553",
        "luminance('#f80')|0.38868318886144393",
        "luminance('rgb(10, 20, 30)')|0.006585790668061925",
        "luminance('rgb(100%, 0%, 0%)')|0.2126",
        // Either side of the knee: channel 10 takes the linear branch and channel 11 the power one.
        "luminance('#0a0a0a')|0.003035269835488375",
        "luminance('#0b0b0b')|0.0033465357638991604",
        // The vector that tells the two knees apart. A lightness of 4% is a channel of exactly
        // 0.04, which is above WCAG's 0.03928 and below sRGB's 0.04045, so the linear branch would
        // give 0.0030959752 here instead — right to five digits and wrong after that.
        "luminance('hsl(0, 0%, 4%)')|0.0030954995810608937",
        // Fractional channels, which is what an hsl colour has. Rounding them to bytes first gives
        // 0.12512359 rather than this.
        "luminance('hsl(210, 50%, 40%)')|0.1250645743288924",
        // Opacity is not a channel and does not dim anything.
        "luminance('hsla(120, 60%, 25%, 0.5)')|0.09788192429901331",
        // NaN, serialized by JSON.stringify as null: d3 blanks the channels of a colour it cannot
        // read *and* of one whose opacity is zero, so a transparent colour is not black.
        "luminance('nonsense')|null",
        "luminance('transparent')|null",
        "luminance('none')|null",
        "luminance('rgba(255, 0, 0, 0)')|null",
        // ---- contrast ----
        // The WCAG ratio, which is symmetric: the brighter colour always goes on top, so writing
        // the pair either way round gives the same answer and it is never below 1.
        "contrast('#000000','#ffffff')|21",
        "contrast('#ffffff','#000000')|21",
        "contrast('steelblue','steelblue')|1",
        // The pair the grouped-bar chart asks about, and why the answer is not obvious: white and
        // black are within 1% of each other against Vega's default blue, so an approximation that
        // is right to two digits still picks the wrong label colour.
        "contrast('white','#4c78a8')|4.6059511274406955",
        "contrast('black','#4c78a8')|4.559318893960711",
        "contrast('white','#f58518')|2.5452396422570263",
        "contrast('black','#f58518')|8.250696575422642",
        "contrast('hsl(210, 50%, 40%)','#0a0a0a')|3.3009085250613452",
        // A luminance of NaN carries through both the max and the min, so the ratio is NaN and
        // every comparison against it is false — which is how an unreadable colour behaves.
        "contrast('nonsense','white')|null",
        "contrast('transparent','white')|null",
        // ---- containerSize ----
        // No DOM, so this is upstream's own headless answer: two absent values, not [0, 0].
        "containerSize()|[null,null]",
        "length(containerSize())|2",
        "isValid(containerSize()[0])|false",
        "containerSize()[0] == null|true",
      ],
  )
  fun `functions match upstream Vega`(source: String, expected: String) {
    assertEquals(expected, evaluate(source), "expression: $source")
  }

  @Test
  fun `array and object results match upstream`() {
    assertEquals("[\"a\",\"b\",\"c\"]", evaluate("split(\"a,b,c\",\",\")"))
    assertEquals("[3,2,1]", evaluate("reverse([1,2,3])"))
    assertEquals("[2,3]", evaluate("slice([1,2,3,4],1,3)"))
    assertEquals("[3,4]", evaluate("slice([1,2,3,4],-2)"))
    assertEquals("[1,5]", evaluate("clampRange([1,5],0,10)"))
    assertEquals("[0,10]", evaluate("clampRange([-5,5],0,10)"))
    assertEquals("[0,10]", evaluate("clampRange([0,20],0,10)"))
    assertEquals("\"abcd…\"", evaluate("truncate(\"abcdefgh\",5)"))
  }

  @Test
  fun `operators containing the csv delimiter match upstream`() {
    // These cannot live in the CSV table: `|` and `||` are the table's own delimiter, and an empty
    // string literal does not survive CSV quoting.
    assertEquals("3", evaluate("1 | 2 ^ 3 & 4"))
    // `||` reads as two delimiters in the CSV table, so it lives here too.
    assertEquals("\"fallback\"", evaluate("\"\" || \"fallback\""))
    assertEquals("\"x\"", evaluate("\"x\" || \"y\""))
    assertEquals("0", evaluate("+\"\""))
    assertEquals("0", evaluate("toNumber(\"\")"))
  }

  @Test
  fun `object literals support both quoted and bare keys`() {
    assertEquals("1", evaluate("{\"a\": 1}.a"))
    assertEquals("1", evaluate("{a: 1}[\"a\"]"))
  }

  /**
   * Date functions, pinned against upstream.
   *
   * Only the `utc` half is checked here, deliberately: the local-time half reads whatever zone the
   * machine is in, so a reference vector for it would pass in one place and fail in another. The
   * two share every line of implementation past the zone they are handed, and `TimeScaleTest`
   * covers the zone-dependent behaviour with zones it names explicitly.
   */
  @ParameterizedTest(name = "{0}")
  @CsvSource(
    delimiter = '|',
    value =
      [
        // ---- accessors: month and day-of-week are zero-based, quarter and day-of-year are not
        // ----
        "utcyear(utc(2026, 2, 14))|2026",
        "utcquarter(utc(2026, 2, 14))|1",
        "utcmonth(utc(2026, 2, 14))|2",
        "utcdate(utc(2026, 2, 14))|14",
        "utcday(utc(2026, 2, 14))|6",
        "utcdayofyear(utc(2026, 2, 14))|73",
        "utchours(utc(2026, 2, 14, 9, 5, 3, 250))|9",
        "utcminutes(utc(2026, 2, 14, 9, 5, 3, 250))|5",
        "utcseconds(utc(2026, 2, 14, 9, 5, 3, 250))|3",
        "utcmilliseconds(utc(2026, 2, 14, 9, 5, 3, 250))|250",
        // ---- construction rolls over, as JavaScript's Date does ----
        "utc(2026, 12, 1)|1798761600000",
        "utc(2026, 0, 32)|1769904000000",
        "utc(2026, 0, 1) - utc(2025, 11, 31)|86400000",
        "time(utc(2026, 0, 1))|1767225600000",
        // ---- formatting ----
        "utcFormat(utc(2026, 2, 14, 9, 5), '%Y-%m-%d %H:%M')|\"2026-03-14 09:05\"",
        "utcFormat(utc(2026, 0, 5), '%B %d, %Y')|\"January 05, 2026\"",
        "utcFormat(utc(2026, 0, 5), '%a %b %e')|\"Mon Jan  5\"",
        "utcFormat(utc(2026, 0, 5), '%j')|\"005\"",
        "utcFormat(utc(2026, 6, 4, 13, 7), '%I:%M %p')|\"01:07 PM\"",
        "utcFormat(utc(2026, 6, 4), '%y')|\"26\"",
        // `%q` is Vega's own directive and `%U` counts Sunday boundaries from the year's start, so
        // a year opening on a Sunday has no week 0 and one opening on a Tuesday does.
        "utcFormat(utc(2012, 4, 15), 'Q%q W%U')|\"Q2 W20\"",
        "utcFormat(utc(2012, 0, 1), 'W%U')|\"W01\"",
        "utcFormat(utc(2013, 0, 1), 'W%U')|\"W00\"",
        "utcFormat(utc(2013, 0, 5), 'W%U')|\"W00\"",
        "utcFormat(utc(2013, 0, 6), 'W%U')|\"W01\"",
        "utcFormat(utc(2026, 11, 31), 'Q%q W%U')|\"Q4 W52\"",
        // ---- the format a set of time units is labelled with ----
        // The longest recognised *run* wins, which is what collapses three units into one field,
        // and the units are put in calendar order before the runs are matched.
        "timeUnitSpecifier(['day'], {hours:'%H'})|\"%a\"",
        "timeUnitSpecifier(['year','month'])|\"%Y-%m\"",
        "timeUnitSpecifier(['date','year','month'])|\"%Y-%m-%d\"",
        "timeUnitSpecifier(['quarter'])|\"Q%q\"",
        "timeUnitSpecifier(['week'])|\"W%U\"",
        "timeUnitSpecifier(['hours','minutes'])|\"%H:%M\"",
        "timeUnitSpecifier(['date','hours'])|\"%d %H:00\"",
        "timeUnitSpecifier(['seconds'])|\":%S\"",
        "timeUnitSpecifier('month')|\"%b\"",
        // ---- moving a date by whole units ----
        // The step defaults to one and is *floored*; an absent argument is not `Number()`-coerced
        // to zero, which would hand the date straight back. Both forms below are the ones a
        // specification writes, and the two-argument one is the common one.
        "timeFormat(timeOffset('day', datetime(2019,2,31)), '%Y-%m-%d %H:%M')|\"2019-04-01 00:00\"",
        "timeFormat(timeOffset('day', datetime(2019,2,31), 2), '%Y-%m-%d %H:%M')|\"2019-04-02 00:00\"",
        "timeFormat(timeOffset('day', datetime(2019,2,31), 0), '%Y-%m-%d %H:%M')|\"2019-03-31 00:00\"",
        "timeFormat(timeOffset('day', datetime(2019,2,31), null), '%Y-%m-%d %H:%M')|\"2019-04-01 00:00\"",
        "timeFormat(timeOffset('day', datetime(2019,2,31), 1.7), '%Y-%m-%d %H:%M')|\"2019-04-01 00:00\"",
        "timeFormat(timeOffset('day', datetime(2019,2,31), -1), '%Y-%m-%d %H:%M')|\"2019-03-30 00:00\"",
        // ---- reading ----
        "toDate('2026-01-05T00:00:00Z')|1767571200000",
        "utcyear(toDate('2026-01-05T00:00:00Z'))|2026",
        "utcyear(1767225600000)|2026",
      ],
  )
  fun `date functions match upstream`(expression: String, expected: String) {
    assertEquals(expected, evaluate(expression), expression)
  }

  /**
   * `indata` against a dataset holding one of every value kind, pinned against upstream.
   *
   * The point of the table is the coercion. Upstream indexes a dataset by the field value coerced
   * to a string and looks the argument up the same way, so `indata('t', 'k', 1)` finds the row
   * whose `k` is the *string* `"1"`, and the boolean `true` finds the string `"true"`. An
   * implementation that compares with `===` — which is what the documented "matches value" suggests
   * — returns nothing for four of these rows and looks perfectly reasonable while doing it.
   *
   * The result is a **count**, not a boolean: `'a'` appears twice and upstream answers 2.
   */
  @ParameterizedTest(name = "{0}")
  @CsvSource(
    delimiter = '|',
    value =
      [
        "indata('t', 'k', 'a')|2",
        "indata('t', 'k', 'b')|1",
        "indata('t', 'k', 'zzz')|null",
        // The row whose k is the string "1", found by the number 1.
        "indata('t', 'k', 1)|1",
        // The row whose k is the number 5, found by either spelling.
        "indata('t', 'k', 5)|1",
        "indata('t', 'k', '5')|1",
        "indata('t', 'k', null)|1",
        "indata('t', 'k', true)|1",
        "indata('t', 'k', 'true')|1",
        "indata('t', 'n', 3)|1",
        "indata('t', 'n', '3')|1",
        // A field no row has: upstream groups them all under one absent key, which nothing matches.
        "indata('t', 'nosuchfield', 'a')|null",
        "if(indata('t', 'k', 'a'), 'yes', 'no')|\"yes\"",
        "if(indata('t', 'k', 'zzz'), 'yes', 'no')|\"no\"",
      ],
  )
  fun `indata matches upstream`(expression: String, expected: String) {
    val result = compiler.compile(expression)
    assertTrue(result is ExpressionResult.Compiled, "failed to parse '$expression': $result")
    assertEquals(
      expected,
      asJson((result as ExpressionResult.Compiled).expression.evaluate(IndataScope)),
      expression,
    )
  }

  /** The dataset the `indata` table is read against, matching the one the oracle was run on. */
  private object IndataScope : ExpressionScope {
    override val datum: VegaValue = VegaValue.EmptyObject

    override fun signal(name: String): VegaValue = VegaValue.Null

    private fun row(k: VegaValue, n: Double): VegaValue =
      VegaValue.Obj(linkedMapOf("k" to k, "n" to VegaValue.Num(n)))

    private val rows =
      listOf(
        row(VegaValue.Str("a"), 1.0),
        row(VegaValue.Str("a"), 2.0),
        row(VegaValue.Str("b"), 3.0),
        row(VegaValue.Str("1"), 4.0),
        row(VegaValue.Num(5.0), 5.0),
        row(VegaValue.Null, 6.0),
        row(VegaValue.Bool(true), 7.0),
      )

    override fun dataset(name: String): List<VegaValue> = if (name == "t") rows else emptyList()
  }
}
