package dev.aster.vega.expression

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

/**
 * The seeded stream, pinned against upstream's own.
 *
 * Generated by `vega.setRandom(vega.randomLCG(42))` and evaluating the same expressions in a view,
 * which is the only thing that settles two questions reading the code cannot: that the multiplier
 * overflows 2^53 and the sequence depends on how JavaScript rounds it, and that `sampleNormal`
 * keeps Box-Muller's second value between calls, so three normals cost two pairs of uniforms rather
 * than three.
 */
class RandomStreamTest {

  @Test
  fun `the seeded sequence is upstream's`() {
    val stream = RandomStream(RandomStream.DEFAULT_SEED)
    assertEquals(0.5823075997560786, stream.next(), 0.0)
    assertEquals(0.6101966954815186, stream.next(), 0.0)
    assertEquals(0.912484144751208, stream.next(), 0.0)
    assertEquals(15.537503978953467, stream.sampleUniform(10.0, 20.0), 0.0)
    assertEquals(-0.9603135884155702, stream.sampleNormal(0.0, 1.0), 0.0)
    assertEquals(0.32628673218300047, stream.sampleNormal(0.0, 1.0), 0.0)
    assertEquals(0.6589567580785941, stream.sampleNormal(0.0, 1.0), 0.0)
    assertEquals(0.4131097247034061, stream.sampleLogNormal(0.0, 1.0), 0.0)
  }
}
